"""Generation-time output linter for Nova MPG bundles (deck .pptx + workbook
.xlsx).

Parses the ALREADY-GENERATED bytes (never re-runs generation) and reports a
list of findings -- the class of client-facing defect this exists to catch
(raw snake_case leaking into a cell, "(s)" pluralization artifacts, a
fabricated "beating benchmark" badge next to a "--"/"Varies" comparison,
near-duplicate competitor counter-strategy prose, a zero-hire channel
showing a numeric cost-per-hire, ...) shipped TWICE in past bundles before
being caught by a human reviewer. This module is that reviewer, running on
every generation.

Public API:
    run_bundle_qa(pptx_bytes: bytes | None, xlsx_bytes: bytes | None,
                   data: dict) -> list[dict]

Each finding is ``{"severity": "critical" | "warn", "code": str,
"message": str, "location": str}``. ``severity="critical"`` is reserved for
defects that are unambiguous and client-visible (a snake_case token, a
footing mismatch, a fabricated comparison badge, near-duplicate prose,
etc.) -- the kind that should gate a release. ``severity="warn"`` is used
for heuristic/pattern-based checks (ellipsis truncation, a "(N markets)"
count mismatch) that are worth surfacing but carry a higher false-positive
risk and should not, on their own, block generation.

This module NEVER raises on a malformed/absent bundle -- a bundle that
fails to parse is itself reported as a critical finding, not an exception,
so callers (app.py's generation pipeline) can call this unconditionally
without an extra try/except around the call itself (though app.py still
wraps the whole call, belt-and-suspenders, since third-party parsers are
out of this module's control).
"""

from __future__ import annotations

import difflib
import io
import re
from typing import Any

try:
    from pptx import Presentation
except ImportError:  # pragma: no cover -- python-pptx is a hard runtime dep
    Presentation = None  # type: ignore[assignment,misc]

try:
    import openpyxl
except ImportError:  # pragma: no cover -- openpyxl is a hard runtime dep
    openpyxl = None  # type: ignore[assignment]

import display_format
import plan_geo

try:
    from ppt_generator import _is_ai_training_plan
except ImportError:  # pragma: no cover -- defensive only
    def _is_ai_training_plan(_data: dict) -> bool:
        return False


Finding = dict[str, Any]

# ---------------------------------------------------------------------------
# Shared regexes / vocab
# ---------------------------------------------------------------------------
# NOTE: the literal spec regex r'\b[a-z0-9]+_[a-z0-9]+\b' only matches a
# token with EXACTLY one underscore -- \b is a \w/\W transition, underscore
# IS a \w char, so a token with 2+ underscores (e.g. "cdl_drivers_hourly")
# has no internal \b for the fixed two-group pattern to anchor on and the
# literal regex silently never matches it. Using a repeating group instead
# (one-or-more "_word" segments) catches every snake_case token the literal
# regex catches PLUS multi-underscore ones -- a strict superset, matching
# the check's actual intent ("no snake_case tokens... anywhere").
_SNAKE_CASE_RE = re.compile(r"\b[a-z0-9]+(?:_[a-z0-9]+)+\b")
_URL_OR_EMAIL_RE = re.compile(r"https?://|www\.|[\w.+-]+@[\w-]+\.[\w.-]+")
_S_PAREN_RE = re.compile(r"\(s\)")
_MARKETS_PAREN_RE = re.compile(r"\((\d+)\s+markets?\)", re.IGNORECASE)
_MID_WORD_ELLIPSIS_RE = re.compile(r"[a-zA-Z](\.\.\.|…)$")
_MANY_DECIMALS_RE = re.compile(r"\d+\.\d{3,}")
_DOLLAR_POINT_ZERO_K_RE = re.compile(r"\$\d+(?:,\d{3})*\.0K\b")
_DURATION_LABEL_RE = re.compile(
    r"([A-Za-z0-9 .,~-]*?)\(~\s*(\d+)\s*weeks?\)"
)
_AI_TRAINING_VOCAB = (
    "ai trainer",
    "ai training",
    "data labeling",
    "data annotation",
    "activation volumes",
    "rlhf",
)


def _finding(
    severity: str, code: str, message: str, location: str
) -> Finding:
    return {
        "severity": severity,
        "code": code,
        "message": message,
        "location": location,
    }


def _is_ignorable_for_snake_case(text: str) -> bool:
    return bool(_URL_OR_EMAIL_RE.search(text))


# ---------------------------------------------------------------------------
# Text extraction
# ---------------------------------------------------------------------------
class _TextUnit:
    """One piece of extracted text plus enough position/context to run the
    structural (row-clustering) checks."""

    __slots__ = ("text", "location", "slide_idx", "top", "left")

    def __init__(
        self,
        text: str,
        location: str,
        slide_idx: int = -1,
        top: int = 0,
        left: int = 0,
    ) -> None:
        self.text = text
        self.location = location
        self.slide_idx = slide_idx
        self.top = top
        self.left = left


def _iter_pptx_texts(pptx_bytes: bytes, findings: list[Finding]) -> list[_TextUnit]:
    units: list[_TextUnit] = []
    if Presentation is None:
        findings.append(
            _finding(
                "critical",
                "pptx_parser_unavailable",
                "python-pptx is not importable -- cannot QA the deck",
                "deck",
            )
        )
        return units
    try:
        prs = Presentation(io.BytesIO(pptx_bytes))
    except Exception as exc:  # noqa: BLE001 -- report, never crash the caller
        findings.append(
            _finding(
                "critical",
                "pptx_parse_failed",
                f"Could not open the generated deck: {exc!r}",
                "deck",
            )
        )
        return units

    def _walk(shapes: Any, slide_idx: int, path: str) -> None:
        for shape in shapes:
            shape_name = getattr(shape, "name", "shape")
            loc = f"slide {slide_idx} / {path}{shape_name}"
            top = int(getattr(shape, "top", 0) or 0)
            left = int(getattr(shape, "left", 0) or 0)
            if getattr(shape, "shape_type", None) is not None and getattr(
                shape, "shape_type", None
            ) == 6:  # MSO_SHAPE_TYPE.GROUP
                try:
                    _walk(shape.shapes, slide_idx, f"{path}{shape_name}/")
                except Exception:  # noqa: BLE001
                    pass
            if getattr(shape, "has_text_frame", False):
                for pi, para in enumerate(shape.text_frame.paragraphs):
                    txt = "".join(r.text for r in para.runs) or para.text
                    if txt and txt.strip():
                        units.append(
                            _TextUnit(txt, f"{loc} para {pi}", slide_idx, top, left)
                        )
            if getattr(shape, "has_table", False):
                table = shape.table
                for ri, row in enumerate(table.rows):
                    for ci, cell in enumerate(row.cells):
                        txt = cell.text
                        if txt and txt.strip():
                            units.append(
                                _TextUnit(
                                    txt,
                                    f"{loc} table r{ri}c{ci}",
                                    slide_idx,
                                    top + ri,  # keep rows distinguishable
                                    left + ci,
                                )
                            )

    for si, slide in enumerate(prs.slides, start=1):
        try:
            _walk(slide.shapes, si, "")
        except Exception as exc:  # noqa: BLE001
            findings.append(
                _finding(
                    "warn",
                    "pptx_slide_walk_failed",
                    f"Could not fully walk slide {si}: {exc!r}",
                    f"slide {si}",
                )
            )
    return units


def _iter_xlsx_strings(
    xlsx_bytes: bytes, findings: list[Finding]
) -> tuple[list[_TextUnit], Any]:
    units: list[_TextUnit] = []
    if openpyxl is None:
        findings.append(
            _finding(
                "critical",
                "xlsx_parser_unavailable",
                "openpyxl is not importable -- cannot QA the workbook",
                "workbook",
            )
        )
        return units, None
    try:
        wb = openpyxl.load_workbook(io.BytesIO(xlsx_bytes), data_only=False)
    except Exception as exc:  # noqa: BLE001
        findings.append(
            _finding(
                "critical",
                "xlsx_parse_failed",
                f"Could not open the generated workbook: {exc!r}",
                "workbook",
            )
        )
        return units, None

    for ws in wb.worksheets:
        for row in ws.iter_rows():
            for cell in row:
                if isinstance(cell.value, str) and cell.value.strip():
                    units.append(
                        _TextUnit(
                            cell.value,
                            f"{ws.title}!{cell.coordinate}",
                            top=cell.row,
                            left=cell.column,
                        )
                    )
    return units, wb


# ---------------------------------------------------------------------------
# Generic text-pattern checks (run over BOTH deck + workbook text units)
# ---------------------------------------------------------------------------
def _check_text_patterns(
    units: list[_TextUnit], data: dict, findings: list[Finding]
) -> None:
    authoritative_weeks: int | None = None
    try:
        cw = data.get("campaign_weeks")
        if cw:
            authoritative_weeks = int(cw)
    except (TypeError, ValueError):
        authoritative_weeks = None

    is_us = True
    try:
        is_us = plan_geo.is_us_plan(data)
    except Exception:  # noqa: BLE001
        pass
    is_ai_training = False
    try:
        is_ai_training = _is_ai_training_plan(data)
    except Exception:  # noqa: BLE001
        pass

    for u in units:
        text = u.text
        stripped = text.strip()
        if not stripped:
            continue

        if not _is_ignorable_for_snake_case(text):
            m = _SNAKE_CASE_RE.search(text)
            if m:
                findings.append(
                    _finding(
                        "critical",
                        "snake_case_leak",
                        f"Raw snake_case token {m.group(0)!r} in client-facing "
                        f"text: {stripped[:120]!r}",
                        u.location,
                    )
                )

        if _S_PAREN_RE.search(text):
            findings.append(
                _finding(
                    "critical",
                    "pluralization_artifact",
                    f"'(s)' pluralization artifact left un-resolved: "
                    f"{stripped[:120]!r}",
                    u.location,
                )
            )

        mm = _MARKETS_PAREN_RE.search(text)
        if mm:
            locations = data.get("locations") or []
            n_locations = len(locations) if isinstance(locations, list) else 0
            if n_locations and int(mm.group(1)) != n_locations:
                findings.append(
                    _finding(
                        "warn",
                        "markets_count_mismatch",
                        f"Text says '({mm.group(1)} markets)' but the plan "
                        f"has {n_locations} location(s): {stripped[:120]!r}",
                        u.location,
                    )
                )

        if _MID_WORD_ELLIPSIS_RE.search(text):
            findings.append(
                _finding(
                    "warn",
                    "mid_word_truncation",
                    f"Text appears truncated mid-word: {stripped[-60:]!r}",
                    u.location,
                )
            )

        if _MANY_DECIMALS_RE.search(text):
            findings.append(
                _finding(
                    "critical",
                    "raw_float_precision",
                    f"Raw float with >2 decimals in visible text: "
                    f"{stripped[:120]!r}",
                    u.location,
                )
            )

        if _DOLLAR_POINT_ZERO_K_RE.search(text):
            findings.append(
                _finding(
                    "critical",
                    "dollar_point_zero_k",
                    f"'$X.0K' trailing-zero artifact: {stripped[:120]!r}",
                    u.location,
                )
            )

        low = text.lower()
        if is_us and "non-us market" in low:
            findings.append(
                _finding(
                    "critical",
                    "non_us_text_on_us_plan",
                    f"'non-US market' text present on a US-only plan: "
                    f"{stripped[:120]!r}",
                    u.location,
                )
            )
        if "location advisory" in low:
            findings.append(
                _finding(
                    "critical",
                    "location_advisory_leak",
                    f"'Location advisory' text must never render: "
                    f"{stripped[:120]!r}",
                    u.location,
                )
            )

        if not is_ai_training:
            for phrase in _AI_TRAINING_VOCAB:
                if phrase in low:
                    findings.append(
                        _finding(
                            "critical",
                            "ai_training_vocab_leak",
                            f"AI-training vocabulary {phrase!r} on a "
                            f"non-AI-training plan: {stripped[:120]!r}",
                            u.location,
                        )
                    )
                    break

        dm = _DURATION_LABEL_RE.search(text)
        if dm:
            weeks_str = dm.group(2)
            full_label = dm.group(0)
            try:
                parsed_weeks = display_format.parse_duration_to_weeks(full_label)
            except Exception:  # noqa: BLE001
                parsed_weeks = None
            # 1) The label must parse back to its OWN literal "(~N weeks)"
            #    via display_format.parse_duration_to_weeks (this is what
            #    the task/spec names as the round-trip oracle).
            if parsed_weeks is not None and parsed_weeks != int(weeks_str):
                findings.append(
                    _finding(
                        "critical",
                        "duration_roundtrip_mismatch",
                        f"Duration label {stripped[:80]!r} does not "
                        f"round-trip through "
                        f"display_format.parse_duration_to_weeks "
                        f"(got {parsed_weeks}, printed {weeks_str})",
                        u.location,
                    )
                )
            # 2) The literal week count must match the SAME campaign_weeks
            #    this bundle's rest of the report was built from -- this is
            #    the actual historical defect class (a duration label
            #    drifting from the numeric window everything else in the
            #    bundle is computed against, e.g. an "18 months" plan
            #    whose forecast/timeline silently ran on 72 weeks while the
            #    label said "17 months (~72 weeks)" instead of the correct
            #    78). NOTE: month->weeks conversion is intentionally NOT
            #    re-derived from the label's "N months" prefix here --
            #    fixed marketing buckets (e.g. "6 months" -> 24 weeks, a
            #    4-weeks/month convention) are a legitimate, separate
            #    ladder from the 52/12 free-text conversion, so comparing
            #    against the authoritative campaign_weeks value (rather
            #    than re-parsing the prefix) avoids flagging those
            #    intentional buckets as false positives.
            elif authoritative_weeks and int(weeks_str) != authoritative_weeks:
                findings.append(
                    _finding(
                        "critical",
                        "duration_label_drifted_from_campaign_weeks",
                        f"Duration label {stripped[:80]!r} states "
                        f"{weeks_str} weeks but this bundle's "
                        f"campaign_weeks is {authoritative_weeks}",
                        u.location,
                    )
                )


# ---------------------------------------------------------------------------
# Client-name casing
# ---------------------------------------------------------------------------
def _check_client_name_casing(
    units: list[_TextUnit], data: dict, findings: list[Finding]
) -> None:
    raw = str(data.get("client_name") or "").strip()
    if not raw:
        return
    canonical = display_format.client_display_name(raw)
    if not canonical or canonical == raw:
        return  # nothing to distinguish -- raw casing already canonical
    raw_re = re.compile(r"\b" + re.escape(raw) + r"\b")
    for u in units:
        if raw_re.search(u.text):
            findings.append(
                _finding(
                    "critical",
                    "client_name_wrong_casing",
                    f"Client name appears in raw casing {raw!r} instead of "
                    f"the canonical {canonical!r}: {u.text.strip()[:120]!r}",
                    u.location,
                )
            )


# ---------------------------------------------------------------------------
# Deck: comparison-badge sanity (row-clustering over textbox positions)
# ---------------------------------------------------------------------------
_ROW_TOLERANCE_EMU = 20_000  # ~0.02in -- shapes on the "same row" of a
# hand-laid-out comparison grid land within a few thousand EMU of each
# other's `top`, well under one text line's height.


def _check_comparison_badges(
    pptx_units: list[_TextUnit], findings: list[Finding]
) -> None:
    by_slide: dict[int, list[_TextUnit]] = {}
    for u in pptx_units:
        by_slide.setdefault(u.slide_idx, []).append(u)

    for slide_idx, slide_units in by_slide.items():
        rows: list[list[_TextUnit]] = []
        for u in sorted(slide_units, key=lambda x: x.top):
            placed = False
            for row in rows:
                if abs(row[0].top - u.top) <= _ROW_TOLERANCE_EMU:
                    row.append(u)
                    placed = True
                    break
            if not placed:
                rows.append([u])

        for row in rows:
            if len(row) < 2:
                continue
            row_texts = [r.text for r in row]
            has_beating_badge = any(
                "▲" in t or re.search(r"\bbeating\b", t, re.IGNORECASE)
                for t in row_texts
            )
            has_non_comparable = any(
                t.strip() == "—" or "varies" in t.lower() for t in row_texts
            )
            if has_beating_badge and has_non_comparable:
                findings.append(
                    _finding(
                        "critical",
                        "fabricated_beating_badge",
                        "A 'beating benchmark' badge appears on the same "
                        "row as a non-comparable ('—'/Varies) "
                        f"benchmark value: {row_texts}",
                        row[0].location,
                    )
                )


# ---------------------------------------------------------------------------
# Counter-strategy distinctness (deck cards + workbook column)
# ---------------------------------------------------------------------------
def _check_counter_strategy_distinctness(
    strings: list[tuple[str, str]], findings: list[Finding]
) -> None:
    """``strings`` is a list of (text, location). Flags any pair >85%
    similar via difflib.SequenceMatcher."""
    n = len(strings)
    for i in range(n):
        for j in range(i + 1, n):
            text_i, loc_i = strings[i]
            text_j, loc_j = strings[j]
            if not text_i or not text_j:
                continue
            ratio = difflib.SequenceMatcher(None, text_i, text_j).ratio()
            if ratio > 0.85:
                findings.append(
                    _finding(
                        "critical",
                        "counter_strategy_near_duplicate",
                        f"Counter-strategy text at {loc_i} is {ratio:.0%} "
                        f"similar to the text at {loc_j} -- competitors "
                        f"must not read as interchangeable",
                        loc_i,
                    )
                )


def _collect_pptx_counter_strategies(pptx_units: list[_TextUnit]) -> list[tuple[str, str]]:
    out = []
    for u in pptx_units:
        stripped = u.text.strip()
        if stripped.startswith("Counter:"):
            out.append((stripped[len("Counter:"):].strip(), u.location))
    return out


def _collect_xlsx_counter_strategies(wb: Any) -> list[tuple[str, str]]:
    out: list[tuple[str, str]] = []
    if wb is None:
        return out
    for ws in wb.worksheets:
        header_row = None
        counter_col = None
        for row in ws.iter_rows():
            for cell in row:
                if cell.value == "Counter-Strategy":
                    header_row = cell.row
                    counter_col = cell.column
                    break
            if header_row:
                break
        if not header_row or not counter_col:
            continue
        for row in ws.iter_rows(min_row=header_row + 1):
            for cell in row:
                if cell.column == counter_col and isinstance(cell.value, str):
                    if cell.value.strip():
                        out.append((cell.value.strip(), f"{ws.title}!{cell.coordinate}"))
    return out


# ---------------------------------------------------------------------------
# Workbook footing checks
# ---------------------------------------------------------------------------
def _cell_num(v: Any) -> float | None:
    if isinstance(v, bool):
        return None
    if isinstance(v, (int, float)):
        return float(v)
    return None


def _check_90_day_forecast_footing(wb: Any, findings: list[Finding]) -> None:
    if wb is None or "90-Day Forecast" not in wb.sheetnames:
        return
    ws = wb["90-Day Forecast"]
    rows = list(ws.iter_rows(values_only=False))

    # Both tables on this sheet ("Monthly Projections Overview" and
    # "Per-Channel Monthly Spend Forecast") follow the same shape: a header
    # row with a label column, 3 month columns, and a "Total"/"90-Day
    # Total" column, followed by data rows until a blank row.
    ri = 0
    while ri < len(rows):
        row = rows[ri]
        vals = [c.value for c in row]
        total_col_idx = None
        for ci, v in enumerate(vals):
            if isinstance(v, str) and "total" in v.lower():
                total_col_idx = ci
                break
        looks_like_header = (
            total_col_idx is not None
            and total_col_idx >= 3
            and any(isinstance(v, str) and v in ("Metric", "Channel") for v in vals)
        )
        if looks_like_header:
            label_col_idx = next(
                (ci for ci, v in enumerate(vals) if v in ("Metric", "Channel")),
                None,
            )
            month_cols = list(range(label_col_idx + 1, total_col_idx))
            data_ri = ri + 1
            while data_ri < len(rows):
                data_row = rows[data_ri]
                dvals = [c.value for c in data_row]
                label = dvals[label_col_idx] if label_col_idx < len(dvals) else None
                if not isinstance(label, str) or not label.strip():
                    break
                # CPA-style *rate* rows are not additive across months --
                # only check rows the generator itself treats as additive
                # (Spend/Applications/Hires/channel-dollar rows never carry
                # "Cost" or "CPA"/"CPH"/"CPC" in the label).
                if not re.search(r"\bcp[achv]\b|cost per", label, re.IGNORECASE):
                    month_vals = [
                        _cell_num(dvals[ci]) if ci < len(dvals) else None
                        for ci in month_cols
                    ]
                    total_val = (
                        _cell_num(dvals[total_col_idx])
                        if total_col_idx < len(dvals)
                        else None
                    )
                    if (
                        total_val is not None
                        and all(v is not None for v in month_vals)
                    ):
                        actual_sum = sum(month_vals)  # type: ignore[arg-type]
                        if abs(actual_sum - total_val) > 0.51:
                            findings.append(
                                _finding(
                                    "critical",
                                    "forecast_footing_mismatch",
                                    f"Row {label!r} monthly values "
                                    f"{month_vals} sum to {actual_sum:,.2f} "
                                    f"but the printed total is "
                                    f"{total_val:,.2f}",
                                    f"{ws.title}!row{data_row[0].row}",
                                )
                            )
                data_ri += 1
            ri = data_ri
            continue
        ri += 1


def _parse_money_str(s: Any) -> float | None:
    if isinstance(s, (int, float)) and not isinstance(s, bool):
        return float(s)
    if not isinstance(s, str):
        return None
    cleaned = re.sub(r"[^0-9.\-]", "", s)
    if not cleaned or cleaned in ("-", "."):
        return None
    try:
        return float(cleaned)
    except ValueError:
        return None


def _check_executive_summary_budget_footing(
    wb: Any, findings: list[Finding]
) -> None:
    if wb is None or "Executive Summary" not in wb.sheetnames:
        return
    ws = wb["Executive Summary"]
    rows = list(ws.iter_rows(values_only=False))

    total_budget: float | None = None
    for ri, row in enumerate(rows):
        vals = [c.value for c in row]
        if any(v == "Total Budget" for v in vals):
            # Value lives one row ABOVE the label, same column (this
            # sheet's KV-block convention -- see excel_v2._write_kv_row).
            label_ci = next(ci for ci, v in enumerate(vals) if v == "Total Budget")
            if ri > 0:
                total_budget = _parse_money_str(rows[ri - 1][label_ci].value)
            break
    if total_budget is None:
        return

    header_row_idx = None
    amount_col = None
    channel_col = None
    for ri, row in enumerate(rows):
        vals = [c.value for c in row]
        if "Channel" in vals and "Amount" in vals:
            header_row_idx = ri
            channel_col = vals.index("Channel")
            amount_col = vals.index("Amount")
            break
    if header_row_idx is None or amount_col is None:
        return

    channel_sum = 0.0
    ri = header_row_idx + 1
    while ri < len(rows):
        vals = [c.value for c in rows[ri]]
        label = vals[channel_col] if channel_col < len(vals) else None
        if not isinstance(label, str) or not label.strip():
            break
        if label.strip().lower() == "total":
            break
        amt = _cell_num(vals[amount_col]) if amount_col < len(vals) else None
        if amt is not None:
            channel_sum += amt
        ri += 1

    if channel_sum and abs(channel_sum - total_budget) > max(1.0, total_budget * 0.005):
        findings.append(
            _finding(
                "critical",
                "exec_summary_budget_footing_mismatch",
                f"Executive Summary channel Amount column sums to "
                f"{channel_sum:,.2f} but the stated Total Budget is "
                f"{total_budget:,.2f}",
                f"{ws.title}!Budget Allocation",
            )
        )


# ---------------------------------------------------------------------------
# Zero-hire honesty
# ---------------------------------------------------------------------------
def _check_zero_hire_honesty(wb: Any, findings: list[Finding]) -> None:
    if wb is None:
        return
    for ws in wb.worksheets:
        rows = list(ws.iter_rows(values_only=False))
        for ri, row in enumerate(rows):
            vals = [c.value for c in row]
            hires_col = None
            cph_col = None
            for ci, v in enumerate(vals):
                if isinstance(v, str):
                    vl = v.lower()
                    if hires_col is None and (
                        "proj. hires" in vl or vl.strip() == "hires"
                    ):
                        hires_col = ci
                    if cph_col is None and (
                        "cost per hire" in vl or vl.strip() in ("cph", "cost/hire")
                    ):
                        cph_col = ci
            if hires_col is None or cph_col is None:
                continue
            for dri in range(ri + 1, len(rows)):
                dvals = [c.value for c in rows[dri]]
                if hires_col >= len(dvals) or cph_col >= len(dvals):
                    continue
                hires_val = _cell_num(dvals[hires_col])
                if hires_val is None:
                    continue
                if hires_val == 0:
                    cph_val = dvals[cph_col]
                    cph_num = _cell_num(cph_val)
                    if cph_num is not None and cph_num > 0:
                        findings.append(
                            _finding(
                                "critical",
                                "zero_hire_nonzero_cph",
                                f"Row with 0 projected hires shows a "
                                f"numeric Cost Per Hire ({cph_val!r}) "
                                f"instead of '—'",
                                f"{ws.title}!row{rows[dri][0].row}",
                            )
                        )


# ---------------------------------------------------------------------------
# Public entry point
# ---------------------------------------------------------------------------
def run_bundle_qa(
    pptx_bytes: bytes | None, xlsx_bytes: bytes | None, data: dict
) -> list[Finding]:
    """Lint an already-generated bundle. Never raises -- parse failures and
    all other problems are reported as findings, not exceptions, so callers
    can invoke this unconditionally right after bundle assembly."""
    findings: list[Finding] = []
    data = data if isinstance(data, dict) else {}

    pptx_units: list[_TextUnit] = []
    xlsx_units: list[_TextUnit] = []
    wb = None

    if pptx_bytes:
        try:
            pptx_units = _iter_pptx_texts(pptx_bytes, findings)
        except Exception as exc:  # noqa: BLE001
            findings.append(
                _finding(
                    "critical", "pptx_qa_crashed", f"{exc!r}", "deck"
                )
            )

    if xlsx_bytes:
        try:
            xlsx_units, wb = _iter_xlsx_strings(xlsx_bytes, findings)
        except Exception as exc:  # noqa: BLE001
            findings.append(
                _finding(
                    "critical", "xlsx_qa_crashed", f"{exc!r}", "workbook"
                )
            )

    all_units = pptx_units + xlsx_units
    try:
        _check_text_patterns(all_units, data, findings)
    except Exception as exc:  # noqa: BLE001
        findings.append(_finding("warn", "text_pattern_check_crashed", f"{exc!r}", ""))

    try:
        _check_client_name_casing(all_units, data, findings)
    except Exception as exc:  # noqa: BLE001
        findings.append(_finding("warn", "client_name_check_crashed", f"{exc!r}", ""))

    try:
        _check_comparison_badges(pptx_units, findings)
    except Exception as exc:  # noqa: BLE001
        findings.append(_finding("warn", "comparison_badge_check_crashed", f"{exc!r}", ""))

    try:
        counter_strings = _collect_pptx_counter_strategies(
            pptx_units
        ) + _collect_xlsx_counter_strategies(wb)
        _check_counter_strategy_distinctness(counter_strings, findings)
    except Exception as exc:  # noqa: BLE001
        findings.append(_finding("warn", "counter_strategy_check_crashed", f"{exc!r}", ""))

    try:
        _check_90_day_forecast_footing(wb, findings)
    except Exception as exc:  # noqa: BLE001
        findings.append(_finding("warn", "forecast_footing_check_crashed", f"{exc!r}", ""))

    try:
        _check_executive_summary_budget_footing(wb, findings)
    except Exception as exc:  # noqa: BLE001
        findings.append(_finding("warn", "exec_summary_footing_check_crashed", f"{exc!r}", ""))

    try:
        _check_zero_hire_honesty(wb, findings)
    except Exception as exc:  # noqa: BLE001
        findings.append(_finding("warn", "zero_hire_check_crashed", f"{exc!r}", ""))

    return findings


__all__ = ["run_bundle_qa"]
