"""Generation-time output linter for Nova MPG bundles (deck .pptx + workbook
.xlsx).

Parses the ALREADY-GENERATED bytes (never re-runs generation) and reports a
list of findings -- the class of client-facing defect this exists to catch
(raw snake_case leaking into a cell, "(s)" pluralization artifacts, a
fabricated "beating benchmark" badge next to a "--"/"Varies" comparison,
near-duplicate competitor counter-strategy prose, a zero-hire channel
showing a numeric cost-per-hire, ...) shipped TWICE in past bundles before
being caught by a human reviewer. This module is that reviewer, running on
every generation.

Public API:
    run_bundle_qa(pptx_bytes: bytes | None, xlsx_bytes: bytes | None,
                   data: dict) -> list[dict]

Each finding is ``{"severity": "critical" | "warn", "code": str,
"message": str, "location": str}``. ``severity="critical"`` is reserved for
defects that are unambiguous and client-visible (a snake_case token, a
footing mismatch, a fabricated comparison badge, near-duplicate prose,
etc.) -- the kind that should gate a release. ``severity="warn"`` is used
for heuristic/pattern-based checks (ellipsis truncation, a "(N markets)"
count mismatch) that are worth surfacing but carry a higher false-positive
risk and should not, on their own, block generation.

This module NEVER raises on a malformed/absent bundle -- a bundle that
fails to parse is itself reported as a critical finding, not an exception,
so callers (app.py's generation pipeline) can call this unconditionally
without an extra try/except around the call itself (though app.py still
wraps the whole call, belt-and-suspenders, since third-party parsers are
out of this module's control).
"""

from __future__ import annotations

import difflib
import io
import re
from datetime import datetime
from typing import Any

try:
    from pptx import Presentation
except ImportError:  # pragma: no cover -- python-pptx is a hard runtime dep
    Presentation = None  # type: ignore[assignment,misc]

try:
    import openpyxl
except ImportError:  # pragma: no cover -- openpyxl is a hard runtime dep
    openpyxl = None  # type: ignore[assignment]

import display_format
import plan_currency
import plan_geo

try:
    from ppt_generator import _is_ai_training_plan
except ImportError:  # pragma: no cover -- defensive only

    def _is_ai_training_plan(_data: dict) -> bool:
        return False


Finding = dict[str, Any]

# ---------------------------------------------------------------------------
# Shared regexes / vocab
# ---------------------------------------------------------------------------
# NOTE: the literal spec regex r'\b[a-z0-9]+_[a-z0-9]+\b' only matches a
# token with EXACTLY one underscore -- \b is a \w/\W transition, underscore
# IS a \w char, so a token with 2+ underscores (e.g. "cdl_drivers_hourly")
# has no internal \b for the fixed two-group pattern to anchor on and the
# literal regex silently never matches it. Using a repeating group instead
# (one-or-more "_word" segments) catches every snake_case token the literal
# regex catches PLUS multi-underscore ones -- a strict superset, matching
# the check's actual intent ("no snake_case tokens... anywhere").
_SNAKE_CASE_RE = re.compile(r"\b[a-z0-9]+(?:_[a-z0-9]+)+\b")
_URL_OR_EMAIL_RE = re.compile(r"https?://|www\.|[\w.+-]+@[\w-]+\.[\w.-]+")
_S_PAREN_RE = re.compile(r"\(s\)")
_MARKETS_PAREN_RE = re.compile(r"\((\d+)\s+markets?\)", re.IGNORECASE)
_MID_WORD_ELLIPSIS_RE = re.compile(r"[a-zA-Z](\.\.\.|…)$")
_MANY_DECIMALS_RE = re.compile(r"\d+\.\d{3,}")
_DOLLAR_POINT_ZERO_K_RE = re.compile(r"\$\d+(?:,\d{3})*\.0K\b")
_DURATION_LABEL_RE = re.compile(r"([A-Za-z0-9 .,~-]*?)\(~\s*(\d+)\s*weeks?\)")
# prod-Atria defect: an unbounded ("Ongoing") duration spliced straight into
# the "<budget> over <duration>" template read as the ungrammatical "over
# Ongoing" (no verb, no fixed length to be "over"), and a raw unformatted
# budget (e.g. the int 25000, never routed through display_format.fmt_money)
# leaked onto the slide as bare digits immediately before "over" -- see
# ppt_generator._interpolate_next_steps / _is_unbounded_duration and
# excel_v2._is_unbounded_duration, which now avoid generating this text.
# Kept here too as a standing artifact guard so this exact defect class can
# never ship silently again, regardless of which generator path produced it.
# Case-sensitive on "Ongoing" -- the deliberately-lowercased "ongoing" this
# codebase's fixed phrasing now uses ("$25K, ongoing" / "on an ongoing
# basis") must NOT false-positive here.
_OVER_ONGOING_RE = re.compile(r"over\s+Ongoing\b")
_RAW_NUMBER_BEFORE_OVER_RE = re.compile(r"\b\d{4,7}\s+over\b")
_AI_TRAINING_VOCAB = (
    "ai trainer",
    "ai training",
    "data labeling",
    "data annotation",
    "activation volumes",
    "rlhf",
)

# ---------------------------------------------------------------------------
# RULE 1 (us_data_on_non_us_plan): US-only macro/holiday vocabulary leaking
# onto a plan with NO US location at all -- the mirror, in the OTHER
# direction, of the non_us_text_on_us_plan check above (bundle_qa.py:279
# already resolves plan_geo.is_us_plan(data) but the existing check at
# bundle_qa.py:398 only ever used it for "non-US market" text on a US
# plan).
# ---------------------------------------------------------------------------
_US_ONLY_MARKERS: tuple[str, ...] = (
    "Fed Funds",
    "CPI Index",
    "BLS",
    "JOLTS",
    "Bls Sector Code",
    "Total Employment Us",
    "Job Openings Rate Jolts",
    "Quits Rate Jolts",
    "federal minimum wage",
    "Thanksgiving",
    "Memorial Day",
    "Spring break",
)
_US_ONLY_MARKER_RES: tuple[re.Pattern, ...] = tuple(
    re.compile(r"\b" + re.escape(m) + r"\b", re.IGNORECASE) for m in _US_ONLY_MARKERS
)

# ---------------------------------------------------------------------------
# RULE 2 (currency_symbol_mixing).
# ---------------------------------------------------------------------------
# A currency glyph NOT immediately preceded by a letter -- "US$"/"NZ$"/"A$"/
# "HK$"/"MX$"/"C$"/"S$"/"R$" are all honest, explicitly-marked local-context
# prefixes (see ppt_generator._mark_usd, :1836, and this module's docstring
# on local-context figures) -- only a BARE glyph (no letter prefix at all)
# can only be a mistaken hardcoded symbol.
_CUR_GLYPHS = "$£€₹¥"
_CUR_GLYPH_RE = re.compile("(?<![A-Za-z])[" + re.escape(_CUR_GLYPHS) + "]")
# Real shipped defect: a bare "$" glyph paired with a non-USD ISO code in
# parentheses, e.g. "$42,000 (GBP)" -- self-contradictory regardless of the
# plan's own currency (a "$" can never legitimately denote a GBP/AUD/MXN
# amount), so this shape is checked unconditionally, independent of the
# length-blob cutoff below.
_DOLLAR_WITH_FOREIGN_CODE_RE = re.compile(
    r"(?<![A-Za-z])\$[\d,]+(?:\.\d+)?\s*\(([A-Z]{3})\)"
)
# Separates a short plan-figure sentence/cell (deck copy, a benchmark
# range, a localized salary cell) from the sprawling multi-topic KB
# research-citation dumps (Gen Z workforce-trend surveys, Indeed/LinkedIn/
# Appcast platform-stat appendices, ...) that legitimately cite third-party
# USD figures inline and are not this plan's own presented numbers.
# Calibrated against the real shipped Uber bundle: every genuine target
# cell/sentence is well under this length; every KB-citation blob
# comfortably exceeds it (measured gap runs from ~230 chars to ~635 chars
# with nothing in between).
_CUR_BLOB_LEN_CUTOFF = 300

# ---------------------------------------------------------------------------
# RULE 3 (campaign_duration_incoherence).
# ---------------------------------------------------------------------------
_WEEK_RANGE_RE = re.compile(r"\bWeeks?\s+(\d+)\s*[-–]\s*(\d+)\b", re.IGNORECASE)
_MONTH_RANGE_RE = re.compile(r"\b(\d+)\s*[-–]\s*(\d+)\s*months?\b", re.IGNORECASE)
_DATE_RANGE_RE = re.compile(
    r"([A-Za-z]{3,9}\s+\d{1,2},\s*\d{4})\s*-\s*([A-Za-z]{3,9}\s+\d{1,2},\s*\d{4})"
)
# Wide enough to absorb the 24-vs-26-week "fixed marketing bucket vs 52/12
# free-text" wobble the existing duration_label_drifted check already
# treats as legitimate (see its comment above), nowhere near wide enough to
# swallow the real shipped defect's 4-vs-12-vs-13-week spread.
_DURATION_SPREAD_TOLERANCE_WEEKS = 3

# ---------------------------------------------------------------------------
# RULE 5 (competitor_count_contradiction).
# ---------------------------------------------------------------------------
_COMPETITOR_COUNT_RE = re.compile(r"Competitor Count:\s*(\d+)", re.IGNORECASE)


def _finding(severity: str, code: str, message: str, location: str) -> Finding:
    return {
        "severity": severity,
        "code": code,
        "message": message,
        "location": location,
    }


def _is_ignorable_for_snake_case(text: str) -> bool:
    return bool(_URL_OR_EMAIL_RE.search(text))


# ---------------------------------------------------------------------------
# Text extraction
# ---------------------------------------------------------------------------
class _TextUnit:
    """One piece of extracted text plus enough position/context to run the
    structural (row-clustering) checks."""

    __slots__ = ("text", "location", "slide_idx", "top", "left")

    def __init__(
        self,
        text: str,
        location: str,
        slide_idx: int = -1,
        top: int = 0,
        left: int = 0,
    ) -> None:
        self.text = text
        self.location = location
        self.slide_idx = slide_idx
        self.top = top
        self.left = left


def _iter_pptx_texts(pptx_bytes: bytes, findings: list[Finding]) -> list[_TextUnit]:
    units: list[_TextUnit] = []
    if Presentation is None:
        findings.append(
            _finding(
                "critical",
                "pptx_parser_unavailable",
                "python-pptx is not importable -- cannot QA the deck",
                "deck",
            )
        )
        return units
    try:
        prs = Presentation(io.BytesIO(pptx_bytes))
    except Exception as exc:  # noqa: BLE001 -- report, never crash the caller
        findings.append(
            _finding(
                "critical",
                "pptx_parse_failed",
                f"Could not open the generated deck: {exc!r}",
                "deck",
            )
        )
        return units

    def _walk(shapes: Any, slide_idx: int, path: str) -> None:
        for shape in shapes:
            shape_name = getattr(shape, "name", "shape")
            loc = f"slide {slide_idx} / {path}{shape_name}"
            top = int(getattr(shape, "top", 0) or 0)
            left = int(getattr(shape, "left", 0) or 0)
            if (
                getattr(shape, "shape_type", None) is not None
                and getattr(shape, "shape_type", None) == 6
            ):  # MSO_SHAPE_TYPE.GROUP
                try:
                    _walk(shape.shapes, slide_idx, f"{path}{shape_name}/")
                except Exception:  # noqa: BLE001
                    pass
            if getattr(shape, "has_text_frame", False):
                for pi, para in enumerate(shape.text_frame.paragraphs):
                    txt = "".join(r.text for r in para.runs) or para.text
                    if txt and txt.strip():
                        units.append(
                            _TextUnit(txt, f"{loc} para {pi}", slide_idx, top, left)
                        )
            if getattr(shape, "has_table", False):
                table = shape.table
                for ri, row in enumerate(table.rows):
                    for ci, cell in enumerate(row.cells):
                        txt = cell.text
                        if txt and txt.strip():
                            units.append(
                                _TextUnit(
                                    txt,
                                    f"{loc} table r{ri}c{ci}",
                                    slide_idx,
                                    top + ri,  # keep rows distinguishable
                                    left + ci,
                                )
                            )

    for si, slide in enumerate(prs.slides, start=1):
        try:
            _walk(slide.shapes, si, "")
        except Exception as exc:  # noqa: BLE001
            findings.append(
                _finding(
                    "warn",
                    "pptx_slide_walk_failed",
                    f"Could not fully walk slide {si}: {exc!r}",
                    f"slide {si}",
                )
            )
    return units


def _iter_xlsx_strings(
    xlsx_bytes: bytes, findings: list[Finding]
) -> tuple[list[_TextUnit], Any]:
    units: list[_TextUnit] = []
    if openpyxl is None:
        findings.append(
            _finding(
                "critical",
                "xlsx_parser_unavailable",
                "openpyxl is not importable -- cannot QA the workbook",
                "workbook",
            )
        )
        return units, None
    try:
        wb = openpyxl.load_workbook(io.BytesIO(xlsx_bytes), data_only=False)
    except Exception as exc:  # noqa: BLE001
        findings.append(
            _finding(
                "critical",
                "xlsx_parse_failed",
                f"Could not open the generated workbook: {exc!r}",
                "workbook",
            )
        )
        return units, None

    for ws in wb.worksheets:
        for row in ws.iter_rows():
            for cell in row:
                if isinstance(cell.value, str) and cell.value.strip():
                    units.append(
                        _TextUnit(
                            cell.value,
                            f"{ws.title}!{cell.coordinate}",
                            top=cell.row,
                            left=cell.column,
                        )
                    )
    return units, wb


# ---------------------------------------------------------------------------
# Generic text-pattern checks (run over BOTH deck + workbook text units)
# ---------------------------------------------------------------------------
def _check_text_patterns(
    units: list[_TextUnit], data: dict, findings: list[Finding]
) -> None:
    authoritative_weeks: int | None = None
    try:
        cw = data.get("campaign_weeks")
        if cw:
            authoritative_weeks = int(cw)
    except (TypeError, ValueError):
        authoritative_weeks = None

    is_us = True
    try:
        is_us = plan_geo.is_us_plan(data)
    except Exception:  # noqa: BLE001
        pass
    is_ai_training = False
    try:
        is_ai_training = _is_ai_training_plan(data)
    except Exception:  # noqa: BLE001
        pass

    for u in units:
        text = u.text
        stripped = text.strip()
        if not stripped:
            continue

        if not _is_ignorable_for_snake_case(text):
            m = _SNAKE_CASE_RE.search(text)
            if m:
                findings.append(
                    _finding(
                        "critical",
                        "snake_case_leak",
                        f"Raw snake_case token {m.group(0)!r} in client-facing "
                        f"text: {stripped[:120]!r}",
                        u.location,
                    )
                )

        if _S_PAREN_RE.search(text):
            findings.append(
                _finding(
                    "critical",
                    "pluralization_artifact",
                    f"'(s)' pluralization artifact left un-resolved: "
                    f"{stripped[:120]!r}",
                    u.location,
                )
            )

        mm = _MARKETS_PAREN_RE.search(text)
        if mm:
            locations = data.get("locations") or []
            n_locations = len(locations) if isinstance(locations, list) else 0
            n_mentioned = int(mm.group(1))
            # A "(N market(s))" parenthetical can legitimately describe a
            # SUBSET of the plan's locations -- e.g. a Risk Register title
            # "High Competition (1 market)" out of 6 total, sourced from
            # competitor_map's hiring_intensity classification, not from
            # the plan's full location list. Only an *impossible* count --
            # more markets mentioned than the plan actually has -- is a
            # genuine defect; any count <= n_locations is a valid subset
            # and must not be flagged.
            if n_locations and n_mentioned > n_locations:
                findings.append(
                    _finding(
                        "warn",
                        "markets_count_mismatch",
                        f"Text says '({display_format.fmt_count(n_mentioned, 'market')})' "
                        f"but the plan has only {n_locations} location(s): "
                        f"{stripped[:120]!r}",
                        u.location,
                    )
                )

        if _MID_WORD_ELLIPSIS_RE.search(text):
            findings.append(
                _finding(
                    "warn",
                    "mid_word_truncation",
                    f"Text appears truncated mid-word: {stripped[-60:]!r}",
                    u.location,
                )
            )

        if _MANY_DECIMALS_RE.search(text):
            findings.append(
                _finding(
                    "critical",
                    "raw_float_precision",
                    f"Raw float with >2 decimals in visible text: "
                    f"{stripped[:120]!r}",
                    u.location,
                )
            )

        if _DOLLAR_POINT_ZERO_K_RE.search(text):
            findings.append(
                _finding(
                    "critical",
                    "dollar_point_zero_k",
                    f"'$X.0K' trailing-zero artifact: {stripped[:120]!r}",
                    u.location,
                )
            )

        if _OVER_ONGOING_RE.search(text):
            findings.append(
                _finding(
                    "critical",
                    "over_ongoing_grammar",
                    f"Ungrammatical unbounded-duration phrasing 'over "
                    f"Ongoing': {stripped[:120]!r}",
                    u.location,
                )
            )

        if _RAW_NUMBER_BEFORE_OVER_RE.search(text):
            findings.append(
                _finding(
                    "critical",
                    "raw_number_before_over",
                    f"Raw unformatted number directly before 'over' "
                    f"(budget should be money-formatted): "
                    f"{stripped[:120]!r}",
                    u.location,
                )
            )

        low = text.lower()
        if is_us and "non-us market" in low:
            findings.append(
                _finding(
                    "critical",
                    "non_us_text_on_us_plan",
                    f"'non-US market' text present on a US-only plan: "
                    f"{stripped[:120]!r}",
                    u.location,
                )
            )
        if "location advisory" in low:
            findings.append(
                _finding(
                    "critical",
                    "location_advisory_leak",
                    f"'Location advisory' text must never render: "
                    f"{stripped[:120]!r}",
                    u.location,
                )
            )

        if not is_ai_training:
            for phrase in _AI_TRAINING_VOCAB:
                if phrase in low:
                    findings.append(
                        _finding(
                            "critical",
                            "ai_training_vocab_leak",
                            f"AI-training vocabulary {phrase!r} on a "
                            f"non-AI-training plan: {stripped[:120]!r}",
                            u.location,
                        )
                    )
                    break

        dm = _DURATION_LABEL_RE.search(text)
        if dm:
            weeks_str = dm.group(2)
            full_label = dm.group(0)
            try:
                parsed_weeks = display_format.parse_duration_to_weeks(full_label)
            except Exception:  # noqa: BLE001
                parsed_weeks = None
            # 1) The label must parse back to its OWN literal "(~N weeks)"
            #    via display_format.parse_duration_to_weeks (this is what
            #    the task/spec names as the round-trip oracle).
            if parsed_weeks is not None and parsed_weeks != int(weeks_str):
                findings.append(
                    _finding(
                        "critical",
                        "duration_roundtrip_mismatch",
                        f"Duration label {stripped[:80]!r} does not "
                        f"round-trip through "
                        f"display_format.parse_duration_to_weeks "
                        f"(got {parsed_weeks}, printed {weeks_str})",
                        u.location,
                    )
                )
            # 2) The literal week count must match the SAME campaign_weeks
            #    this bundle's rest of the report was built from -- this is
            #    the actual historical defect class (a duration label
            #    drifting from the numeric window everything else in the
            #    bundle is computed against, e.g. an "18 months" plan
            #    whose forecast/timeline silently ran on 72 weeks while the
            #    label said "17 months (~72 weeks)" instead of the correct
            #    78). NOTE: month->weeks conversion is intentionally NOT
            #    re-derived from the label's "N months" prefix here --
            #    fixed marketing buckets (e.g. "6 months" -> 24 weeks, a
            #    4-weeks/month convention) are a legitimate, separate
            #    ladder from the 52/12 free-text conversion, so comparing
            #    against the authoritative campaign_weeks value (rather
            #    than re-parsing the prefix) avoids flagging those
            #    intentional buckets as false positives.
            elif authoritative_weeks and int(weeks_str) != authoritative_weeks:
                findings.append(
                    _finding(
                        "critical",
                        "duration_label_drifted_from_campaign_weeks",
                        f"Duration label {stripped[:80]!r} states "
                        f"{weeks_str} weeks but this bundle's "
                        f"campaign_weeks is {authoritative_weeks}",
                        u.location,
                    )
                )


# ---------------------------------------------------------------------------
# Client-name casing
# ---------------------------------------------------------------------------
def _check_client_name_casing(
    units: list[_TextUnit], data: dict, findings: list[Finding]
) -> None:
    raw = str(data.get("client_name") or "").strip()
    if not raw:
        return
    canonical = display_format.client_display_name(raw)
    if not canonical or canonical == raw:
        return  # nothing to distinguish -- raw casing already canonical
    raw_re = re.compile(r"\b" + re.escape(raw) + r"\b")
    for u in units:
        if raw_re.search(u.text):
            findings.append(
                _finding(
                    "critical",
                    "client_name_wrong_casing",
                    f"Client name appears in raw casing {raw!r} instead of "
                    f"the canonical {canonical!r}: {u.text.strip()[:120]!r}",
                    u.location,
                )
            )


# ---------------------------------------------------------------------------
# Deck: comparison-badge sanity (row-clustering over textbox positions)
# ---------------------------------------------------------------------------
_ROW_TOLERANCE_EMU = 20_000  # ~0.02in -- shapes on the "same row" of a
# hand-laid-out comparison grid land within a few thousand EMU of each
# other's `top`, well under one text line's height.


def _check_comparison_badges(
    pptx_units: list[_TextUnit], findings: list[Finding]
) -> None:
    by_slide: dict[int, list[_TextUnit]] = {}
    for u in pptx_units:
        by_slide.setdefault(u.slide_idx, []).append(u)

    for slide_idx, slide_units in by_slide.items():
        rows: list[list[_TextUnit]] = []
        for u in sorted(slide_units, key=lambda x: x.top):
            placed = False
            for row in rows:
                if abs(row[0].top - u.top) <= _ROW_TOLERANCE_EMU:
                    row.append(u)
                    placed = True
                    break
            if not placed:
                rows.append([u])

        for row in rows:
            if len(row) < 2:
                continue
            row_texts = [r.text for r in row]
            has_beating_badge = any(
                "▲" in t or re.search(r"\bbeating\b", t, re.IGNORECASE)
                for t in row_texts
            )
            has_non_comparable = any(
                t.strip() == "—" or "varies" in t.lower() for t in row_texts
            )
            if has_beating_badge and has_non_comparable:
                findings.append(
                    _finding(
                        "critical",
                        "fabricated_beating_badge",
                        "A 'beating benchmark' badge appears on the same "
                        "row as a non-comparable ('—'/Varies) "
                        f"benchmark value: {row_texts}",
                        row[0].location,
                    )
                )


# ---------------------------------------------------------------------------
# Counter-strategy distinctness (deck cards + workbook column)
# ---------------------------------------------------------------------------
# S92 fix: the original check compared every counter-strategy string
# ALL-PAIRS across the deck, the Market Intelligence sheet, AND the Quality
# Intelligence sheet. But the same competitor legitimately carries the same
# composed sentence across those artifacts -- e.g. "ManpowerGroup" gets the
# same insight_composer output on the deck's competitor card, in Market
# Intelligence's Competitor Analysis row, and in Quality Intelligence's
# Competitive Landscape row, because that's intentional single-sourcing
# (one composer, one set of inputs), not interchangeable-sounding
# competitors. A pair should only be compared -- and only flagged -- when
# both (a) it comes from the SAME artifact view (the deck is one view;
# each worksheet TABLE is its own view, since a sheet can host more than
# one Counter-Strategy table) and (b) it names two DIFFERENT competitor
# identities. When identity can't be established for either side, the pair
# is skipped rather than flagged -- absence of evidence isn't evidence of
# a "sounds interchangeable" defect.
def _norm_identity(identity: str | None) -> str | None:
    if not isinstance(identity, str):
        return None
    normalized = identity.strip().lower()
    return normalized or None


def _check_counter_strategy_distinctness(
    strings: list[tuple[str, str, str | None, str]], findings: list[Finding]
) -> None:
    """``strings`` is a list of (text, location, identity, view) tuples.
    Flags any pair >85% similar via difflib.SequenceMatcher, but only
    within the same ``view`` and only when ``identity`` is collectable on
    both sides and differs between them."""
    by_view: dict[str, list[tuple[str, str, str | None]]] = {}
    for text, loc, identity, view in strings:
        by_view.setdefault(view, []).append((text, loc, identity))

    for items in by_view.values():
        n = len(items)
        for i in range(n):
            for j in range(i + 1, n):
                text_i, loc_i, id_i = items[i]
                text_j, loc_j, id_j = items[j]
                if not text_i or not text_j:
                    continue
                norm_i, norm_j = _norm_identity(id_i), _norm_identity(id_j)
                if norm_i is None or norm_j is None:
                    continue  # identity not collectable -- skip, don't flag
                if norm_i == norm_j:
                    continue  # same competitor within one view -- expected
                ratio = difflib.SequenceMatcher(None, text_i, text_j).ratio()
                if ratio > 0.85:
                    findings.append(
                        _finding(
                            "critical",
                            "counter_strategy_near_duplicate",
                            f"Counter-strategy text at {loc_i} is {ratio:.0%} "
                            f"similar to the text at {loc_j} -- competitors "
                            f"must not read as interchangeable",
                            loc_i,
                        )
                    )


def _collect_pptx_counter_strategies(
    pptx_units: list[_TextUnit],
) -> list[tuple[str, str, str | None, str]]:
    """Returns (text, location, identity, view) tuples. ``view`` is always
    "deck" -- the whole deck is one artifact for distinctness purposes.

    ``identity`` is the competitor name for the card this "Counter:" line
    belongs to. ppt_generator._build_slide_competitive_landscape writes
    each card's shapes in a fixed sequence -- name textbox, then "Why: ..."
    textbox, then "Counter: ..." textbox -- with no other text interleaved
    between one card's name and its own counter line, so "the most recent
    unit that isn't itself a 'Why:'/'Counter:' line" is that card's name,
    regardless of what came before it on the slide.
    """
    out: list[tuple[str, str, str | None, str]] = []
    pending_identity: str | None = None
    for u in pptx_units:
        stripped = u.text.strip()
        if not stripped:
            continue
        if stripped.startswith("Counter:"):
            out.append(
                (
                    stripped[len("Counter:") :].strip(),
                    u.location,
                    pending_identity,
                    "deck",
                )
            )
        elif stripped.startswith("Why:"):
            continue  # descriptive line between name and counter -- not an identity
        else:
            pending_identity = stripped
    return out


_IDENTITY_HEADER_CANDIDATES = {
    "name",
    "competitor",
    "competitor name",
    "employer",
    "employers",
    "top employer",
    "top employers",
    "company",
}


def _cell_style_signature(cell: Any) -> tuple[Any, Any, bool] | None:
    """A (fill_type, fg_color_key, bold) signature used ONLY to recognize
    "this cell is styled like a _write_table_header cell" -- i.e. to detect
    a NEW table's header row reusing the same column letter, not for any
    general-purpose style comparison. Returns None if styling can't be
    introspected (defensive -- must never crash the QA pass)."""
    try:
        fill = cell.fill
        fg = getattr(fill, "fgColor", None)
        fg_key = getattr(fg, "rgb", None) or getattr(fg, "theme", None)
        fill_type = getattr(fill, "fill_type", None)
        bold = bool(cell.font and cell.font.bold)
        return (fill_type, fg_key, bold)
    except Exception:  # noqa: BLE001
        return None


def _collect_xlsx_counter_strategies(
    wb: Any,
) -> list[tuple[str, str, str | None, str]]:
    """Returns (text, location, identity, view) tuples.

    S92 fix: the original version found the FIRST 'Counter-Strategy' header
    in a worksheet and then collected every subsequent cell in that column
    letter for the rest of the sheet, with no stop condition. On sheets
    where a LATER, unrelated table reuses the same column letter for a
    different field (Quality Intelligence's "Role Difficulty
    Classification" table puts "Location Modifier" in the same column F
    that the "Competitive Landscape & Counter-Strategies" table above it
    used for "Counter-Strategy"), every value from that unrelated column
    got misread as competitor counter-strategy prose. Bound collection to
    the table: stop at the first fully-blank row after data starts, or at
    the next row styled like a table header (same fill+bold signature as
    the header cell this table started from) -- whichever comes first.

    ``identity`` is the row's competitor/employer-name column value,
    located by matching the header row against
    ``_IDENTITY_HEADER_CANDIDATES``; needed by
    ``_check_counter_strategy_distinctness`` to tell "same competitor
    legitimately repeats similar prose" apart from "two different
    competitors read as interchangeable". ``view`` is a per-table key
    (worksheet + header row) so distinctness is only ever checked within
    one table, never across worksheets/artifacts.
    """
    out: list[tuple[str, str, str | None, str]] = []
    if wb is None:
        return out

    for ws in wb.worksheets:
        in_table = False
        counter_col: int | None = None
        identity_col: int | None = None
        header_sig: tuple[Any, Any, bool] | None = None
        view = ""

        for row in ws.iter_rows():
            if not in_table:
                header_cell = next(
                    (c for c in row if c.value == "Counter-Strategy"), None
                )
                if header_cell is None:
                    continue
                counter_col = header_cell.column
                header_sig = _cell_style_signature(header_cell)
                view = f"{ws.title}#{header_cell.row}"
                identity_col = None
                for c in row:
                    if (
                        isinstance(c.value, str)
                        and c.value.strip().lower() in _IDENTITY_HEADER_CANDIDATES
                    ):
                        identity_col = c.column
                        break
                in_table = True
                continue

            # Already inside a table -- decide whether this row still
            # belongs to it before (maybe) collecting from it.
            if all(c.value in (None, "") for c in row):
                in_table = False
                continue

            counter_cell = next((c for c in row if c.column == counter_col), None)
            if counter_cell is None:
                continue

            if (
                header_sig is not None
                and isinstance(counter_cell.value, str)
                and counter_cell.value.strip()
                and _cell_style_signature(counter_cell) == header_sig
            ):
                # A different table's header row, reusing this column
                # letter and the same header styling -- this table ended
                # one row up.
                in_table = False
                continue

            if isinstance(counter_cell.value, str) and counter_cell.value.strip():
                identity_val: str | None = None
                if identity_col is not None:
                    id_cell = next((c for c in row if c.column == identity_col), None)
                    if id_cell is not None and isinstance(id_cell.value, str):
                        identity_val = id_cell.value.strip() or None
                out.append(
                    (
                        counter_cell.value.strip(),
                        f"{ws.title}!{counter_cell.coordinate}",
                        identity_val,
                        view,
                    )
                )
    return out


# ---------------------------------------------------------------------------
# Workbook footing checks
# ---------------------------------------------------------------------------
def _cell_num(v: Any) -> float | None:
    if isinstance(v, bool):
        return None
    if isinstance(v, (int, float)):
        return float(v)
    return None


def _check_90_day_forecast_footing(wb: Any, findings: list[Finding]) -> None:
    if wb is None or "90-Day Forecast" not in wb.sheetnames:
        return
    ws = wb["90-Day Forecast"]
    rows = list(ws.iter_rows(values_only=False))

    # Both tables on this sheet ("Monthly Projections Overview" and
    # "Per-Channel Monthly Spend Forecast") follow the same shape: a header
    # row with a label column, 3 month columns, and a "Total"/"90-Day
    # Total" column, followed by data rows until a blank row.
    ri = 0
    while ri < len(rows):
        row = rows[ri]
        vals = [c.value for c in row]
        total_col_idx = None
        for ci, v in enumerate(vals):
            if isinstance(v, str) and "total" in v.lower():
                total_col_idx = ci
                break
        looks_like_header = (
            total_col_idx is not None
            and total_col_idx >= 3
            and any(isinstance(v, str) and v in ("Metric", "Channel") for v in vals)
        )
        if looks_like_header:
            label_col_idx = next(
                (ci for ci, v in enumerate(vals) if v in ("Metric", "Channel")),
                None,
            )
            month_cols = list(range(label_col_idx + 1, total_col_idx))
            data_ri = ri + 1
            while data_ri < len(rows):
                data_row = rows[data_ri]
                dvals = [c.value for c in data_row]
                label = dvals[label_col_idx] if label_col_idx < len(dvals) else None
                if not isinstance(label, str) or not label.strip():
                    break
                # CPA-style *rate* rows are not additive across months --
                # only check rows the generator itself treats as additive
                # (Spend/Applications/Hires/channel-dollar rows never carry
                # "Cost" or "CPA"/"CPH"/"CPC" in the label).
                if not re.search(r"\bcp[achv]\b|cost per", label, re.IGNORECASE):
                    month_vals = [
                        _cell_num(dvals[ci]) if ci < len(dvals) else None
                        for ci in month_cols
                    ]
                    total_val = (
                        _cell_num(dvals[total_col_idx])
                        if total_col_idx < len(dvals)
                        else None
                    )
                    if total_val is not None and all(v is not None for v in month_vals):
                        actual_sum = sum(month_vals)  # type: ignore[arg-type]
                        if abs(actual_sum - total_val) > 0.51:
                            findings.append(
                                _finding(
                                    "critical",
                                    "forecast_footing_mismatch",
                                    f"Row {label!r} monthly values "
                                    f"{month_vals} sum to {actual_sum:,.2f} "
                                    f"but the printed total is "
                                    f"{total_val:,.2f}",
                                    f"{ws.title}!row{data_row[0].row}",
                                )
                            )
                data_ri += 1
            ri = data_ri
            continue
        ri += 1


def _parse_money_str(s: Any) -> float | None:
    if isinstance(s, (int, float)) and not isinstance(s, bool):
        return float(s)
    if not isinstance(s, str):
        return None
    cleaned = re.sub(r"[^0-9.\-]", "", s)
    if not cleaned or cleaned in ("-", "."):
        return None
    try:
        return float(cleaned)
    except ValueError:
        return None


def _check_executive_summary_budget_footing(wb: Any, findings: list[Finding]) -> None:
    if wb is None or "Executive Summary" not in wb.sheetnames:
        return
    ws = wb["Executive Summary"]
    rows = list(ws.iter_rows(values_only=False))

    total_budget: float | None = None
    for ri, row in enumerate(rows):
        vals = [c.value for c in row]
        if any(v == "Total Budget" for v in vals):
            # Value lives one row ABOVE the label, same column (this
            # sheet's KV-block convention -- see excel_v2._write_kv_row).
            label_ci = next(ci for ci, v in enumerate(vals) if v == "Total Budget")
            if ri > 0:
                total_budget = _parse_money_str(rows[ri - 1][label_ci].value)
            break
    if total_budget is None:
        return

    header_row_idx = None
    amount_col = None
    channel_col = None
    for ri, row in enumerate(rows):
        vals = [c.value for c in row]
        if "Channel" in vals and "Amount" in vals:
            header_row_idx = ri
            channel_col = vals.index("Channel")
            amount_col = vals.index("Amount")
            break
    if header_row_idx is None or amount_col is None:
        return

    channel_sum = 0.0
    ri = header_row_idx + 1
    while ri < len(rows):
        vals = [c.value for c in rows[ri]]
        label = vals[channel_col] if channel_col < len(vals) else None
        if not isinstance(label, str) or not label.strip():
            break
        if label.strip().lower() == "total":
            break
        amt = _cell_num(vals[amount_col]) if amount_col < len(vals) else None
        if amt is not None:
            channel_sum += amt
        ri += 1

    if channel_sum and abs(channel_sum - total_budget) > max(1.0, total_budget * 0.005):
        findings.append(
            _finding(
                "critical",
                "exec_summary_budget_footing_mismatch",
                f"Executive Summary channel Amount column sums to "
                f"{channel_sum:,.2f} but the stated Total Budget is "
                f"{total_budget:,.2f}",
                f"{ws.title}!Budget Allocation",
            )
        )


# ---------------------------------------------------------------------------
# Zero-hire honesty
# ---------------------------------------------------------------------------
def _check_zero_hire_honesty(wb: Any, findings: list[Finding]) -> None:
    if wb is None:
        return
    for ws in wb.worksheets:
        rows = list(ws.iter_rows(values_only=False))
        for ri, row in enumerate(rows):
            vals = [c.value for c in row]
            hires_col = None
            cph_col = None
            for ci, v in enumerate(vals):
                if isinstance(v, str):
                    vl = v.lower()
                    if hires_col is None and (
                        "proj. hires" in vl or vl.strip() == "hires"
                    ):
                        hires_col = ci
                    if cph_col is None and (
                        "cost per hire" in vl or vl.strip() in ("cph", "cost/hire")
                    ):
                        cph_col = ci
            if hires_col is None or cph_col is None:
                continue
            for dri in range(ri + 1, len(rows)):
                dvals = [c.value for c in rows[dri]]
                if hires_col >= len(dvals) or cph_col >= len(dvals):
                    continue
                hires_val = _cell_num(dvals[hires_col])
                if hires_val is None:
                    continue
                if hires_val == 0:
                    cph_val = dvals[cph_col]
                    cph_num = _cell_num(cph_val)
                    if cph_num is not None and cph_num > 0:
                        findings.append(
                            _finding(
                                "critical",
                                "zero_hire_nonzero_cph",
                                f"Row with 0 projected hires shows a "
                                f"numeric Cost Per Hire ({cph_val!r}) "
                                f"instead of '—'",
                                f"{ws.title}!row{rows[dri][0].row}",
                            )
                        )


# ---------------------------------------------------------------------------
# Recruitment Funnel (S93: funnel-calibration model) footing
# ---------------------------------------------------------------------------
_FUNNEL_STAGE_COLS = (
    "Clicks",
    "Applications",
    "Qualified",
    "Interviews",
    "Hires",
)
_FUNNEL_RATE_COLS = ("App→Qualified", "Qualified→Interview", "Interview→Hire")
_FUNNEL_ROUND_TOL = 1.0  # counts


def _cell_num_or_dash(v: Any) -> float | None:
    """Like ``_cell_num`` but treats an explicit '—' placeholder as 0 (a
    zero-hire channel's Hires/Interview→Hire cell) rather than "not a
    number" -- callers that need to distinguish the two check ``v`` first.
    """
    if isinstance(v, str) and v.strip() == "—":
        return 0.0
    return _cell_num(v)


def _check_recruitment_funnel_footing(wb: Any, findings: list[Finding]) -> None:
    """Validate the ROI Projections "Recruitment Funnel" table (S93):

    - stage counts (Applications -> Qualified -> Interviews -> Hires)
      non-increasing left-to-right on every channel row;
    - each stage count equals round(prev_stage * printed_rate) within a
      rounding tolerance of 1;
    - the TOTAL row of every stage equals the sum of the channel rows
      (largest-remainder rounding is supposed to guarantee this exactly);
    - the Hires column agrees with the existing "Proj. Hires" column in the
      "Per-Channel ROI Analysis" table above, per channel (invariant guard
      -- the funnel model must never disagree with the plan of record).
    """
    if wb is None or "ROI Projections" not in wb.sheetnames:
        return
    ws = wb["ROI Projections"]
    rows = list(ws.iter_rows(values_only=False))

    # ── Gather the existing Per-Channel ROI Analysis hires, by channel name ──
    roi_hires_by_channel: dict[str, float] = {}
    for ri, row in enumerate(rows):
        vals = [c.value for c in row]
        if "Channel Name" not in vals or "Proj. Hires" not in vals:
            continue
        name_ci = vals.index("Channel Name")
        hires_ci = vals.index("Proj. Hires")
        dri = ri + 1
        while dri < len(rows):
            dvals = [c.value for c in rows[dri]]
            label = dvals[name_ci] if name_ci < len(dvals) else None
            if not isinstance(label, str) or not label.strip():
                break
            hv = _cell_num(dvals[hires_ci]) if hires_ci < len(dvals) else None
            if hv is not None:
                roi_hires_by_channel[label.strip()] = hv
            dri += 1
        break

    # ── Locate the Recruitment Funnel table ──
    header_ci: dict[str, int] = {}
    header_ri = None
    for ri, row in enumerate(rows):
        vals = [c.value for c in row]
        if "Channel Name" in vals and all(c in vals for c in _FUNNEL_STAGE_COLS):
            header_ci = {
                name: vals.index(name)
                for name in ("Channel Name", *_FUNNEL_STAGE_COLS, *_FUNNEL_RATE_COLS)
                if name in vals
            }
            header_ri = ri
            break
    if header_ri is None:
        return  # no funnel table -- nothing to check (e.g. zero-budget edge case)

    name_ci = header_ci.get("Channel Name")
    clicks_ci = header_ci.get("Clicks")
    apps_ci = header_ci.get("Applications")
    qual_ci = header_ci.get("Qualified")
    int_ci = header_ci.get("Interviews")
    hires_ci = header_ci.get("Hires")
    r1_ci = header_ci.get("App→Qualified")
    r2_ci = header_ci.get("Qualified→Interview")
    r3_ci = header_ci.get("Interview→Hire")
    if None in (name_ci, apps_ci, qual_ci, int_ci, hires_ci, r1_ci, r2_ci, r3_ci):
        findings.append(
            _finding(
                "warn",
                "recruitment_funnel_header_incomplete",
                "Recruitment Funnel table is missing an expected column",
                f"{ws.title}!row{rows[header_ri][0].row}",
            )
        )
        return

    channel_rows: list[tuple[int, list[Any]]] = []
    total_row: list[Any] | None = None
    ri = header_ri + 1
    while ri < len(rows):
        dvals = [c.value for c in rows[ri]]
        label = dvals[name_ci] if name_ci < len(dvals) else None
        if not isinstance(label, str) or not label.strip():
            break
        if label.strip().upper() == "TOTAL":
            total_row = dvals
            ri += 1
            break
        channel_rows.append((rows[ri][0].row, dvals))
        ri += 1

    sum_clicks = sum_apps = sum_qual = sum_int = sum_hires = 0.0
    for row_num, dvals in channel_rows:
        loc = f"{ws.title}!row{row_num}"
        label = str(dvals[name_ci]).strip()
        clicks = (
            _cell_num(dvals[clicks_ci])
            if clicks_ci is not None and clicks_ci < len(dvals)
            else None
        )
        raw_apps = _cell_num(dvals[apps_ci]) if apps_ci < len(dvals) else None
        qualified = _cell_num(dvals[qual_ci]) if qual_ci < len(dvals) else None
        interviews = _cell_num(dvals[int_ci]) if int_ci < len(dvals) else None
        hires_raw = dvals[hires_ci] if hires_ci < len(dvals) else None
        hires = _cell_num_or_dash(hires_raw)
        r1 = _cell_num(dvals[r1_ci]) if r1_ci < len(dvals) else None
        r2 = _cell_num(dvals[r2_ci]) if r2_ci < len(dvals) else None
        r3_raw = dvals[r3_ci] if r3_ci < len(dvals) else None
        # "—" interview->hire rate means "not modeled" (0-hire row) -- keep
        # it as None rather than coercing to 0.0, so the rate*prev check
        # below is skipped for it rather than asserting hires == 0.
        r3 = (
            None
            if (isinstance(r3_raw, str) and r3_raw.strip() == "—")
            else _cell_num(r3_raw)
        )

        if clicks is not None:
            sum_clicks += clicks
        if raw_apps is not None:
            sum_apps += raw_apps
        if qualified is not None:
            sum_qual += qualified
        if interviews is not None:
            sum_int += interviews
        if hires is not None:
            sum_hires += hires

        # Non-increasing: Applications >= Qualified >= Interviews >= Hires.
        stage_vals = [raw_apps, qualified, interviews, hires]
        if all(v is not None for v in stage_vals):
            for a, b in zip(stage_vals, stage_vals[1:]):
                if b - a > _FUNNEL_ROUND_TOL:
                    findings.append(
                        _finding(
                            "critical",
                            "funnel_stage_not_monotonic",
                            f"Row {label!r} funnel stages {stage_vals} are not "
                            "non-increasing left-to-right",
                            loc,
                        )
                    )
                    break

        # Stage count == round(prev * rate) within tolerance.
        if raw_apps is not None and qualified is not None and r1 is not None:
            expected = round(raw_apps * r1)
            if abs(expected - qualified) > _FUNNEL_ROUND_TOL:
                findings.append(
                    _finding(
                        "critical",
                        "funnel_rate_footing_mismatch",
                        f"Row {label!r}: Qualified={qualified} but "
                        f"Applications({raw_apps}) x App→Qualified({r1}) "
                        f"rounds to {expected}",
                        loc,
                    )
                )
        if qualified is not None and interviews is not None and r2 is not None:
            expected = round(qualified * r2)
            if abs(expected - interviews) > _FUNNEL_ROUND_TOL:
                findings.append(
                    _finding(
                        "critical",
                        "funnel_rate_footing_mismatch",
                        f"Row {label!r}: Interviews={interviews} but "
                        f"Qualified({qualified}) x Qualified→Interview({r2}) "
                        f"rounds to {expected}",
                        loc,
                    )
                )
        if (
            interviews is not None
            and hires is not None
            and r3 is not None
            and not (isinstance(hires_raw, str) and hires_raw.strip() == "—")
        ):
            expected = round(interviews * r3)
            if abs(expected - hires) > _FUNNEL_ROUND_TOL:
                findings.append(
                    _finding(
                        "critical",
                        "funnel_rate_footing_mismatch",
                        f"Row {label!r}: Hires={hires} but "
                        f"Interviews({interviews}) x Interview→Hire({r3}) "
                        f"rounds to {expected}",
                        loc,
                    )
                )

        # Invariant guard: Hires must agree with the ROI table's own
        # Proj. Hires column for the same channel.
        roi_hires = roi_hires_by_channel.get(label)
        if roi_hires is not None and hires is not None and abs(roi_hires - hires) > 0.5:
            findings.append(
                _finding(
                    "critical",
                    "funnel_hires_invariant_mismatch",
                    f"Row {label!r}: Recruitment Funnel Hires={hires} but "
                    f"Per-Channel ROI Analysis Proj. Hires={roi_hires}",
                    loc,
                )
            )

    if total_row is not None:
        total_loc = f"{ws.title}!row{rows[header_ri + 1 + len(channel_rows)][0].row}"
        t_clicks = (
            _cell_num(total_row[clicks_ci])
            if clicks_ci is not None and clicks_ci < len(total_row)
            else None
        )
        t_apps = _cell_num(total_row[apps_ci]) if apps_ci < len(total_row) else None
        t_qual = _cell_num(total_row[qual_ci]) if qual_ci < len(total_row) else None
        t_int = _cell_num(total_row[int_ci]) if int_ci < len(total_row) else None
        t_hires = (
            _cell_num_or_dash(total_row[hires_ci])
            if hires_ci < len(total_row)
            else None
        )

        _pairs = [
            ("Clicks", t_clicks, sum_clicks),
            ("Applications", t_apps, sum_apps),
            ("Qualified", t_qual, sum_qual),
            ("Interviews", t_int, sum_int),
            ("Hires", t_hires, sum_hires),
        ]
        for stage_name, total_val, channel_sum in _pairs:
            if total_val is None:
                continue
            if abs(total_val - channel_sum) > _FUNNEL_ROUND_TOL:
                findings.append(
                    _finding(
                        "critical",
                        "funnel_total_footing_mismatch",
                        f"Recruitment Funnel TOTAL {stage_name}={total_val} but "
                        f"channel rows sum to {channel_sum}",
                        total_loc,
                    )
                )


# ---------------------------------------------------------------------------
# Shared helpers for the five new rules below
# ---------------------------------------------------------------------------
def _resolve_plan_currency(data: dict) -> tuple[str, str]:
    """Resolve the plan's ISO currency code + display symbol, mirroring
    excel_v2._plan_currency_code / ppt_generator._plan_currency_code
    (excel_v2.py:109-160, ppt_generator.py:1507-1545): an explicit
    ``currency_code``/``currency`` field wins; otherwise
    ``plan_currency.currency_for_country`` is tried over
    country/primary_location/locations; otherwise USD. Never raises."""
    code = "USD"
    try:
        explicit = data.get("currency_code") or data.get("currency")
        if isinstance(explicit, str) and explicit.strip():
            code = explicit.strip().upper()
        else:
            candidates: list[str] = []
            for key in ("country", "primary_location"):
                val = data.get(key)
                if isinstance(val, str) and val.strip():
                    candidates.append(val)
            locs = data.get("locations") or []
            if isinstance(locs, (list, tuple)):
                for loc in locs:
                    if isinstance(loc, str) and loc.strip():
                        candidates.append(loc)
                    elif isinstance(loc, dict):
                        country = loc.get("country") or loc.get("location") or ""
                        if isinstance(country, str) and country.strip():
                            candidates.append(country)
            for cand in candidates:
                try:
                    resolved = plan_currency.currency_for_country(cand)
                except Exception:  # noqa: BLE001
                    resolved = None
                if resolved:
                    code = resolved
                    break
    except Exception:  # noqa: BLE001
        code = "USD"
    try:
        symbol = plan_currency.symbol_for_code(code)
    except Exception:  # noqa: BLE001
        symbol = "$"
    return code, symbol


def _has_any_us_location(data: dict) -> bool:
    """True if at least one of the plan's location candidates resolves
    DEFINITIVELY to the US, via plan_geo's own per-candidate resolver --
    NOT plan_geo.is_us_plan, which answers "is EVERY candidate the US" and
    defaults an unresolvable candidate to True, the wrong question here
    ("does the plan have ANY US location at all")."""
    try:
        candidates = plan_geo._gather_candidates(data)
    except Exception:  # noqa: BLE001
        return False
    for raw in candidates:
        try:
            loc_str = plan_geo._extract_str(raw)
            if loc_str and plan_geo._resolve_candidate(loc_str) is True:
                return True
        except Exception:  # noqa: BLE001
            continue
    return False


def _parse_month_date(s: str):
    s = s.strip()
    for fmt in ("%b %d, %Y", "%B %d, %Y"):
        try:
            return datetime.strptime(s, fmt)
        except ValueError:
            continue
    return None


# ---------------------------------------------------------------------------
# RULE 1: us_data_on_non_us_plan
# ---------------------------------------------------------------------------
def _check_us_data_on_non_us_plan(
    units: list[_TextUnit], wb: Any, data: dict, findings: list[Finding]
) -> None:
    """Mirror of the non_us_text_on_us_plan check (bundle_qa.py:398) in the
    OTHER direction. bundle_qa.py:279 already resolves
    ``plan_geo.is_us_plan(data)`` but the existing check only ever used it
    to catch "non-US market" text leaking onto a US-only plan -- it never
    checked US-only macro/BLS/holiday vocabulary leaking onto a plan that
    has NO US location at all.

    Real shipped defect (Uber, 6 non-US markets): the Market Intelligence
    sheet still printed a full US "Industry Metrics" block (Fed Funds Rate,
    CPI Index, BLS JOLTS series, federal minimum wage commentary,
    Thanksgiving/Memorial Day/Spring-break seasonality) and a "Location
    Intelligence" table whose Country column read "United States" for
    every one of its 6 non-US rows.
    """
    is_us = True
    try:
        is_us = plan_geo.is_us_plan(data)
    except Exception:  # noqa: BLE001
        pass
    if is_us:
        return  # the existing non_us_text_on_us_plan rule covers this side

    for u in units:
        text = u.text
        stripped = text.strip()
        if not stripped:
            continue
        for pattern in _US_ONLY_MARKER_RES:
            m = pattern.search(text)
            if m:
                findings.append(
                    _finding(
                        "critical",
                        "us_data_on_non_us_plan",
                        f"US-only marker {m.group(0)!r} present on a "
                        f"non-US plan: {stripped[:120]!r}",
                        u.location,
                    )
                )
                break

    if wb is None or _has_any_us_location(data):
        return
    for ws in wb.worksheets:
        rows = list(ws.iter_rows(values_only=False))
        for ri, row in enumerate(rows):
            for cell in row:
                if cell.value != "Country":
                    continue
                country_col = cell.column
                dri = ri + 1
                while dri < len(rows):
                    val_cell = next(
                        (c for c in rows[dri] if c.column == country_col), None
                    )
                    if (
                        val_cell is None
                        or not isinstance(val_cell.value, str)
                        or not val_cell.value.strip()
                    ):
                        break
                    if val_cell.value.strip() == "United States":
                        findings.append(
                            _finding(
                                "critical",
                                "us_data_on_non_us_plan",
                                "Country column reads 'United States' at "
                                f"{ws.title}!{val_cell.coordinate} but the "
                                "plan has no US location",
                                f"{ws.title}!{val_cell.coordinate}",
                            )
                        )
                    dri += 1


# ---------------------------------------------------------------------------
# RULE 2: currency_symbol_mixing
# ---------------------------------------------------------------------------
def _check_currency_symbol_mixing(
    units: list[_TextUnit], data: dict, findings: list[Finding]
) -> None:
    """Flag a currency symbol in client-facing text that does not match the
    plan's own resolved currency and is not explicitly marked as a
    foreign-denominated benchmark (an "US$"/"NZ$"/"A$"-style letter-
    prefixed form, or the plan's own symbol).

    Real shipped defect (Uber, GBP plan): slide 6 read "£7 average CPA ...
    with $1,626 average cost-per-hire" in the SAME sentence; slides 4 and
    11 quoted bare "$" channel/budget figures the rest of the deck
    correctly rendered in £; the workbook's Location Intelligence table
    paired a bare "$" with a non-USD code in parentheses ("$42,000 (GBP)",
    "$55,000 (AUD)", "$9,500 (MXN)") -- a "$" glyph can never legitimately
    denote a non-USD amount, marked or not, so that shape is checked
    unconditionally below, independent of the plan's own currency.
    """
    plan_code, plan_symbol = _resolve_plan_currency(data)
    plan_symbol = (plan_symbol or "$").strip()

    # Per-sheet "(USD)" marker exemption index, built from this SAME units
    # list (xlsx _TextUnit.top/.left already carry the source cell's
    # row/column -- see _iter_xlsx_strings). Mirrors excel_v2.py's own
    # documented convention (module docstring, ~line 95-98): a fixed-USD
    # figure must "carry an inline '(USD)' marker directly on the
    # figure/header". Two shapes seen in this codebase:
    #   A) same-row KV label, e.g. "Avg Hourly Earnings (USD)" in column B
    #      sanctioning its OWN row's value cell in column D;
    #   B) a table header cell, e.g. "CPC Range (USD)" sanctioning every
    #      data cell below it in the SAME column (Intl Benchmarks E/F/G).
    usd_marked_rows: set[tuple[str, int]] = set()
    usd_marked_cols: set[tuple[str, int]] = set()
    for u in units:
        if "(USD)" not in u.text:
            continue
        sheet = u.location.split("!", 1)[0]
        if u.top:
            usd_marked_rows.add((sheet, u.top))
        if u.left:
            usd_marked_cols.add((sheet, u.left))

    for u in units:
        text = u.text
        stripped = text.strip()
        if not stripped:
            continue

        sheet = u.location.split("!", 1)[0]
        if (sheet, u.top) in usd_marked_rows or (sheet, u.left) in usd_marked_cols:
            continue  # this row/column is an explicitly-marked USD figure

        foreign_code_hit = False
        for m in _DOLLAR_WITH_FOREIGN_CODE_RE.finditer(text):
            code = m.group(1)
            if code != "USD":
                foreign_code_hit = True
                findings.append(
                    _finding(
                        "critical",
                        "currency_symbol_mixing",
                        f"Bare '$' paired with a non-USD code {m.group(0)!r}"
                        f" -- a '$' glyph can never denote a {code} amount: "
                        f"{stripped[:160]!r}",
                        u.location,
                    )
                )
        if foreign_code_hit:
            continue  # already flagged this unit via the more specific shape

        if len(stripped) > _CUR_BLOB_LEN_CUTOFF:
            continue  # KB research-citation blob, not this plan's own figure

        bad_syms = sorted(
            {
                sym
                for sym in (m.group(0) for m in _CUR_GLYPH_RE.finditer(text))
                if sym != plan_symbol
            }
        )
        if bad_syms:
            findings.append(
                _finding(
                    "critical",
                    "currency_symbol_mixing",
                    f"Currency symbol(s) {bad_syms} in client-facing text "
                    f"do not match this plan's currency ({plan_code} "
                    f"{plan_symbol!r}) and are not marked with an explicit "
                    f"foreign-denomination prefix: {stripped[:160]!r}",
                    u.location,
                )
            )


# ---------------------------------------------------------------------------
# RULE 3: campaign_duration_incoherence
# ---------------------------------------------------------------------------
def _check_campaign_duration_incoherence(
    units: list[_TextUnit], wb: Any, findings: list[Finding]
) -> None:
    """Extract every campaign-duration assertion the bundle makes -- a
    labeled "Duration"/"Campaign Duration" KV cell, a "Forecast Period"
    date range, a phased "Week(s) N-M" implementation timeline, an "N-M
    months" free-text mention -- normalise each to weeks, and flag when
    the spread between the smallest and largest exceeds a small tolerance.

    Real shipped defect (Uber): "4 weeks" (Executive Summary + 90-Day
    Forecast's own "Campaign Duration" cell) vs. a "Weeks 1-12" phased
    timeline (deck implementation timeline + 90-Day Forecast's
    "Optimization Milestones") vs. "1-3 months" (deck Next Steps) vs. a
    "Jul 01 - Sep 30, 2026" (~13-week) forecast window -- four different
    numbers for the same campaign.

    The "Forecast Period" date range is collected and reported for context
    (it is one of the brief's four named signals) but does NOT by itself
    gate the spread/tolerance decision below: the "90-Day Forecast" sheet
    is, by design, a fixed ~90-day/13-week ROLLING window regardless of the
    plan's total campaign length (confirmed against this repo's own
    manpower/atria reference bundles -- a 24-week and a 78-week campaign
    both show the identical "Jul 01 - Sep 30, 2026" window), so treating it
    as an authoritative duration claim would false-positive on nearly
    every plan whose campaign isn't coincidentally ~13 weeks long.
    """
    assertions: list[tuple[float, str, str, bool]] = []  # (weeks, label, loc, authoritative)

    if wb is not None and "Executive Summary" in wb.sheetnames:
        ws = wb["Executive Summary"]
        rows = list(ws.iter_rows(values_only=False))
        for ri, row in enumerate(rows):
            for cell in row:
                if cell.value == "Duration" and ri > 0:
                    val_cell = ws.cell(row=cell.row - 1, column=cell.column)
                    if isinstance(val_cell.value, str) and val_cell.value.strip():
                        try:
                            wk = display_format.parse_duration_to_weeks(
                                val_cell.value
                            )
                        except Exception:  # noqa: BLE001
                            wk = 0
                        if wk:
                            assertions.append(
                                (
                                    float(wk),
                                    val_cell.value.strip(),
                                    f"{ws.title}!{val_cell.coordinate}",
                                    True,
                                )
                            )

    if wb is not None and "90-Day Forecast" in wb.sheetnames:
        ws = wb["90-Day Forecast"]
        for row in ws.iter_rows(values_only=False):
            for ci, cell in enumerate(row):
                if cell.value == "Campaign Duration":
                    for other in row[ci + 1 :]:
                        if isinstance(other.value, str) and other.value.strip():
                            try:
                                wk = display_format.parse_duration_to_weeks(
                                    other.value
                                )
                            except Exception:  # noqa: BLE001
                                wk = 0
                            if wk:
                                assertions.append(
                                    (
                                        float(wk),
                                        other.value.strip(),
                                        f"{ws.title}!{other.coordinate}",
                                        True,
                                    )
                                )
                            break
                elif cell.value == "Forecast Period":
                    for other in row[ci + 1 :]:
                        if isinstance(other.value, str) and other.value.strip():
                            dm = _DATE_RANGE_RE.search(other.value)
                            if dm:
                                d1 = _parse_month_date(dm.group(1))
                                d2 = _parse_month_date(dm.group(2))
                                if d1 and d2 and d2 >= d1:
                                    wk = round((d2 - d1).days / 7.0)
                                    if wk:
                                        # Contextual only -- see the
                                        # function docstring: this window
                                        # is a fixed ~90-day rolling lens,
                                        # not itself a duration claim.
                                        assertions.append(
                                            (
                                                float(wk),
                                                other.value.strip(),
                                                f"{ws.title}!{other.coordinate}",
                                                False,
                                            )
                                        )
                            break

    max_phase_week: int | None = None
    max_phase_loc = ""
    for u in units:
        if len(u.text.strip()) > _CUR_BLOB_LEN_CUTOFF:
            continue
        for m in _WEEK_RANGE_RE.finditer(u.text):
            end_wk = int(m.group(2))
            if max_phase_week is None or end_wk > max_phase_week:
                max_phase_week = end_wk
                max_phase_loc = u.location
    if max_phase_week:
        assertions.append(
            (
                float(max_phase_week),
                f"phased timeline ending 'Week {max_phase_week}'",
                max_phase_loc,
                True,
            )
        )

    for u in units:
        stripped = u.text.strip()
        if not stripped or len(stripped) > _CUR_BLOB_LEN_CUTOFF:
            continue
        m = _MONTH_RANGE_RE.search(u.text)
        if not m:
            continue
        lo, hi = int(m.group(1)), int(m.group(2))
        lo_wk = round(lo * 52.0 / 12.0)
        hi_wk = round(hi * 52.0 / 12.0)
        if lo_wk:
            assertions.append(
                (float(lo_wk), f"{m.group(0)!r} (low end)", u.location, True)
            )
        if hi_wk:
            assertions.append(
                (float(hi_wk), f"{m.group(0)!r} (high end)", u.location, True)
            )

    authoritative = [a for a in assertions if a[3]]
    if len(authoritative) < 2:
        return

    weeks_values = [a[0] for a in authoritative]
    spread = max(weeks_values) - min(weeks_values)
    if spread > _DURATION_SPREAD_TOLERANCE_WEEKS:
        detail = "; ".join(
            f"{label} = {wk:.0f}w @ {loc}" for wk, label, loc, _auth in assertions
        )
        findings.append(
            _finding(
                "critical",
                "campaign_duration_incoherence",
                "Campaign duration is stated inconsistently across the "
                f"bundle (spread {spread:.0f} weeks, tolerance "
                f"{_DURATION_SPREAD_TOLERANCE_WEEKS}): {detail}",
                authoritative[0][2],
            )
        )


# ---------------------------------------------------------------------------
# RULE 4: industry_client_conflict
# ---------------------------------------------------------------------------
def _check_industry_client_conflict(data: dict, findings: list[Finding]) -> None:
    """Compare the plan's own resolved industry against what
    ``app.classify_industry`` infers from just the client name + roles
    (ignoring any human-entered industry label).

    Origin defect (Uber + "commercial cab driver"): classify_industry with
    an empty raw_industry confidently resolves to "Rideshare & Gig Economy"
    (legacy_key logistics_supply_chain, via the "uber" keyword) -- but the
    wizard's own "Hospitality & Travel" selection wins unconditionally
    whenever it's passed through as raw_industry (its own keywords
    "hospitality"/"travel" outscore "uber" in the same fuzzy match), and no
    code anywhere compares the two.

    Import is local/defensive: app.py is a very large module with
    module-level side effects (Flask/DB/background-thread init) and itself
    imports bundle_qa lazily inside its generation handler specifically to
    avoid this becoming a circular, heavyweight import (see this module's
    docstring and app.py's own local ``import bundle_qa``).
    """
    try:
        import app as _app
    except Exception:  # noqa: BLE001
        return

    client_name = str(data.get("client_name") or "")
    roles_raw = data.get("target_roles") or data.get("roles") or []
    roles: list[str] = []
    if isinstance(roles_raw, (list, tuple)):
        for r in roles_raw:
            if isinstance(r, dict):
                roles.append(str(r.get("title") or r.get("role") or r))
            else:
                roles.append(str(r))
    elif roles_raw:
        roles.append(str(roles_raw))

    industry_raw = data.get("industry")
    industry_raw = str(industry_raw) if industry_raw else ""

    try:
        selected = _app.classify_industry(industry_raw, client_name, roles)
        implied = _app.classify_industry("", client_name, roles)
    except Exception:  # noqa: BLE001
        return

    selected_key = selected.get("legacy_key")
    implied_key = implied.get("legacy_key")
    if selected_key and implied_key and selected_key != implied_key:
        findings.append(
            _finding(
                "critical",
                "industry_client_conflict",
                f"Plan industry {selected.get('sector')!r} "
                f"(legacy_key={selected_key}) conflicts with the industry "
                f"implied by the client name/roles alone: "
                f"{implied.get('sector')!r} (legacy_key={implied_key})",
                "industry",
            )
        )


# ---------------------------------------------------------------------------
# RULE 5: competitor_count_contradiction
# ---------------------------------------------------------------------------
def _check_competitor_count_contradiction(wb: Any, findings: list[Finding]) -> None:
    """Flag a worksheet's own "Competitor Count: N" summary line
    disagreeing with the number of named competitors actually listed in
    its Competitor Analysis table.

    Real shipped defect (Uber): "Competitor Count: 0" (a stale
    market_positioning snapshot) printed directly below a table naming 5
    competitors (Marriott, Hilton, Hyatt, IHG, Airbnb, from a later
    hardcoded fallback).
    """
    if wb is None:
        return
    for ws in wb.worksheets:
        rows = list(ws.iter_rows(values_only=False))

        stated_count: int | None = None
        stated_loc = ""
        for row in rows:
            for cell in row:
                if isinstance(cell.value, str):
                    m = _COMPETITOR_COUNT_RE.search(cell.value)
                    if m:
                        stated_count = int(m.group(1))
                        stated_loc = f"{ws.title}!{cell.coordinate}"
                        break
            if stated_count is not None:
                break
        if stated_count is None:
            continue

        named: set[str] = set()
        header_ri = None
        name_ci = None
        for ri, row in enumerate(rows):
            vals = [c.value for c in row]
            if "Name" in vals and ("Industry" in vals or "Hiring Activity" in vals):
                header_ri = ri
                name_ci = vals.index("Name")
                break
        if header_ri is not None and name_ci is not None:
            dri = header_ri + 1
            while dri < len(rows):
                dvals = [c.value for c in rows[dri]]
                label = dvals[name_ci] if name_ci < len(dvals) else None
                if not isinstance(label, str) or not label.strip():
                    break
                named.add(label.strip())
                dri += 1

        if named and len(named) != stated_count:
            findings.append(
                _finding(
                    "critical",
                    "competitor_count_contradiction",
                    f"'Competitor Count: {stated_count}' contradicts the "
                    f"{len(named)} named competitor(s) in the Competitor "
                    f"Analysis table ({sorted(named)}): {stated_loc}",
                    stated_loc,
                )
            )


# ---------------------------------------------------------------------------
# Public entry point
# ---------------------------------------------------------------------------
def run_bundle_qa(
    pptx_bytes: bytes | None, xlsx_bytes: bytes | None, data: dict
) -> list[Finding]:
    """Lint an already-generated bundle. Never raises -- parse failures and
    all other problems are reported as findings, not exceptions, so callers
    can invoke this unconditionally right after bundle assembly."""
    findings: list[Finding] = []
    data = data if isinstance(data, dict) else {}

    pptx_units: list[_TextUnit] = []
    xlsx_units: list[_TextUnit] = []
    wb = None

    if pptx_bytes:
        try:
            pptx_units = _iter_pptx_texts(pptx_bytes, findings)
        except Exception as exc:  # noqa: BLE001
            findings.append(_finding("critical", "pptx_qa_crashed", f"{exc!r}", "deck"))

    if xlsx_bytes:
        try:
            xlsx_units, wb = _iter_xlsx_strings(xlsx_bytes, findings)
        except Exception as exc:  # noqa: BLE001
            findings.append(
                _finding("critical", "xlsx_qa_crashed", f"{exc!r}", "workbook")
            )

    all_units = pptx_units + xlsx_units
    try:
        _check_text_patterns(all_units, data, findings)
    except Exception as exc:  # noqa: BLE001
        findings.append(_finding("warn", "text_pattern_check_crashed", f"{exc!r}", ""))

    try:
        _check_client_name_casing(all_units, data, findings)
    except Exception as exc:  # noqa: BLE001
        findings.append(_finding("warn", "client_name_check_crashed", f"{exc!r}", ""))

    try:
        _check_comparison_badges(pptx_units, findings)
    except Exception as exc:  # noqa: BLE001
        findings.append(
            _finding("warn", "comparison_badge_check_crashed", f"{exc!r}", "")
        )

    try:
        counter_strings = _collect_pptx_counter_strategies(
            pptx_units
        ) + _collect_xlsx_counter_strategies(wb)
        _check_counter_strategy_distinctness(counter_strings, findings)
    except Exception as exc:  # noqa: BLE001
        findings.append(
            _finding("warn", "counter_strategy_check_crashed", f"{exc!r}", "")
        )

    try:
        _check_90_day_forecast_footing(wb, findings)
    except Exception as exc:  # noqa: BLE001
        findings.append(
            _finding("warn", "forecast_footing_check_crashed", f"{exc!r}", "")
        )

    try:
        _check_executive_summary_budget_footing(wb, findings)
    except Exception as exc:  # noqa: BLE001
        findings.append(
            _finding("warn", "exec_summary_footing_check_crashed", f"{exc!r}", "")
        )

    try:
        _check_zero_hire_honesty(wb, findings)
    except Exception as exc:  # noqa: BLE001
        findings.append(_finding("warn", "zero_hire_check_crashed", f"{exc!r}", ""))

    try:
        _check_recruitment_funnel_footing(wb, findings)
    except Exception as exc:  # noqa: BLE001
        findings.append(
            _finding("warn", "recruitment_funnel_check_crashed", f"{exc!r}", "")
        )

    try:
        _check_us_data_on_non_us_plan(all_units, wb, data, findings)
    except Exception as exc:  # noqa: BLE001
        findings.append(_finding("warn", "us_data_check_crashed", f"{exc!r}", ""))

    try:
        _check_currency_symbol_mixing(all_units, data, findings)
    except Exception as exc:  # noqa: BLE001
        findings.append(
            _finding("warn", "currency_mixing_check_crashed", f"{exc!r}", "")
        )

    try:
        _check_campaign_duration_incoherence(all_units, wb, findings)
    except Exception as exc:  # noqa: BLE001
        findings.append(
            _finding("warn", "duration_incoherence_check_crashed", f"{exc!r}", "")
        )

    try:
        _check_industry_client_conflict(data, findings)
    except Exception as exc:  # noqa: BLE001
        findings.append(
            _finding("warn", "industry_conflict_check_crashed", f"{exc!r}", "")
        )

    try:
        _check_competitor_count_contradiction(wb, findings)
    except Exception as exc:  # noqa: BLE001
        findings.append(
            _finding("warn", "competitor_count_check_crashed", f"{exc!r}", "")
        )

    return findings


__all__ = ["run_bundle_qa"]
