"""slack_plan_notifier.py -- Slack notification for media plan generation events.

Sends a rich Block Kit message to a designated Slack channel every time
a media plan is successfully generated.

Configuration (env vars):
    SLACK_WEBHOOK_URL       -- Incoming webhook URL (required for notifications)
    SLACK_BOT_TOKEN         -- Bot token alternative (used if webhook not set)
    SLACK_PLAN_CHANNEL      -- Channel for plan notifications (default: #media-plans)

Non-blocking: fires in a daemon thread so generation response is not delayed.
Graceful degradation: logs a warning if Slack credentials are missing, never crashes.
"""

from __future__ import annotations

import json
import logging
import os
import threading
import time
import urllib.error
import urllib.request
from typing import Any, Dict, List, Optional

logger = logging.getLogger(__name__)

# -- Configuration -----------------------------------------------------------

_WEBHOOK_URL: str = os.environ.get("SLACK_WEBHOOK_URL") or ""
_BOT_TOKEN: str = os.environ.get("SLACK_BOT_TOKEN") or ""
_PLAN_CHANNEL: str = os.environ.get("SLACK_PLAN_CHANNEL") or "#media-plans"
_BASE_URL: str = (
    os.environ.get("BASE_URL")
    or os.environ.get("RENDER_EXTERNAL_URL")
    or "https://media-plan-generator.onrender.com"
)
_SEND_TIMEOUT = 15


def _format_budget(budget_val: Any) -> str:
    """Format budget value for display."""
    if not budget_val:
        return "N/A"
    try:
        num = float(str(budget_val).replace(",", "").replace("$", "").strip())
        if num >= 1_000_000:
            return f"${num / 1_000_000:,.1f}M"
        if num >= 1_000:
            return f"${num:,.0f}"
        return f"${num:,.2f}"
    except (ValueError, TypeError):
        return str(budget_val)


def _build_plan_notification_blocks(plan_data: Dict[str, Any]) -> List[Dict[str, Any]]:
    """Build Slack Block Kit blocks for a plan generation notification.

    Args:
        plan_data: Dictionary with plan generation details.

    Returns:
        List of Block Kit block dicts.
    """
    client_name = plan_data.get("client_name") or "Unknown"
    industry = plan_data.get("industry") or "N/A"
    budget = _format_budget(plan_data.get("budget"))
    user_name = plan_data.get("user_name") or "Unknown"
    user_email = plan_data.get("user_email") or "Unknown"
    role_count = plan_data.get("role_count", 0)
    location_count = plan_data.get("location_count", 0)
    channel_count = plan_data.get("channel_count", 0)
    channels_list = plan_data.get("channels_list") or []
    gen_time = plan_data.get("generation_time_seconds", 0)
    job_id = plan_data.get("job_id") or ""
    timestamp = plan_data.get("timestamp") or time.strftime(
        "%Y-%m-%d %H:%M:%S UTC", time.gmtime()
    )
    filename = plan_data.get("filename") or ""

    # Build download URL -- prefer permanent Google Drive link over ephemeral job link
    drive_url = plan_data.get("drive_url") or ""
    download_url = ""
    if drive_url:
        download_url = drive_url
    elif job_id:
        download_url = f"{_BASE_URL.rstrip('/')}/api/jobs/{job_id}"

    # Channels display (show up to 5, then "+N more")
    channels_display = "N/A"
    if channels_list:
        shown = channels_list[:5]
        channels_display = ", ".join(str(c) for c in shown)
        if len(channels_list) > 5:
            channels_display += f" +{len(channels_list) - 5} more"

    blocks: List[Dict[str, Any]] = [
        {
            "type": "header",
            "text": {
                "type": "plain_text",
                "text": "New Media Plan Generated",
                "emoji": True,
            },
        },
        {
            "type": "section",
            "fields": [
                {
                    "type": "mrkdwn",
                    "text": f"*Client:*\n{client_name}",
                },
                {
                    "type": "mrkdwn",
                    "text": f"*Industry:*\n{industry}",
                },
            ],
        },
        {
            "type": "section",
            "fields": [
                {
                    "type": "mrkdwn",
                    "text": f"*Budget:*\n{budget}",
                },
                {
                    "type": "mrkdwn",
                    "text": f"*Generated by:*\n{user_name} ({user_email})",
                },
            ],
        },
        {
            "type": "section",
            "fields": [
                {
                    "type": "mrkdwn",
                    "text": f"*Roles:* {role_count} | *Locations:* {location_count} | *Channels:* {channel_count}",
                },
                {
                    "type": "mrkdwn",
                    "text": f"*Generation time:*\n{gen_time:.1f}s",
                },
            ],
        },
        {
            "type": "section",
            "text": {
                "type": "mrkdwn",
                "text": f"*Channels:* {channels_display}",
            },
        },
    ]

    # Add download button if job_id available
    if download_url:
        blocks.append(
            {
                "type": "actions",
                "elements": [
                    {
                        "type": "button",
                        "text": {
                            "type": "plain_text",
                            "text": f"Download {filename or 'Plan'}",
                            "emoji": True,
                        },
                        "url": download_url,
                        "style": "primary",
                    }
                ],
            }
        )

    # Context footer
    blocks.append(
        {
            "type": "context",
            "elements": [
                {
                    "type": "mrkdwn",
                    "text": f"Nova AI Suite | {timestamp}",
                }
            ],
        }
    )
    blocks.append({"type": "divider"})

    return blocks


def _send_via_webhook(blocks: List[Dict[str, Any]], fallback_text: str) -> bool:
    """Send notification via Slack incoming webhook.

    Args:
        blocks: Block Kit blocks.
        fallback_text: Plain text fallback.

    Returns:
        True if sent successfully.
    """
    if not _WEBHOOK_URL:
        return False

    payload: Dict[str, Any] = {
        "text": fallback_text,
        "blocks": blocks,
    }

    data = json.dumps(payload).encode("utf-8")
    req = urllib.request.Request(_WEBHOOK_URL, data=data, method="POST")
    req.add_header("Content-Type", "application/json")

    try:
        with urllib.request.urlopen(req, timeout=_SEND_TIMEOUT) as resp:
            body = resp.read().decode("utf-8", errors="replace")
            if body.strip().lower() == "ok" or resp.status == 200:
                logger.info("slack_plan_notifier: webhook notification sent")
                return True
            logger.warning(
                "slack_plan_notifier: webhook unexpected response: %s", body[:200]
            )
            return False
    except urllib.error.HTTPError as http_err:
        error_body = ""
        try:
            error_body = http_err.read().decode("utf-8", errors="replace")[:300]
        except OSError:
            pass
        logger.warning(
            "slack_plan_notifier: webhook HTTP %d: %s", http_err.code, error_body
        )
        return False
    except (urllib.error.URLError, OSError, ValueError) as exc:
        logger.warning("slack_plan_notifier: webhook error: %s", exc)
        return False


def _send_via_bot(blocks: List[Dict[str, Any]], fallback_text: str) -> bool:
    """Send notification via Slack Bot API.

    Args:
        blocks: Block Kit blocks.
        fallback_text: Plain text fallback.

    Returns:
        True if sent successfully.
    """
    if not _BOT_TOKEN:
        return False

    payload: Dict[str, Any] = {
        "channel": _PLAN_CHANNEL,
        "text": fallback_text,
        "blocks": blocks,
    }

    data = json.dumps(payload).encode("utf-8")
    url = "https://slack.com/api/chat.postMessage"
    req = urllib.request.Request(url, data=data, method="POST")
    req.add_header("Authorization", f"Bearer {_BOT_TOKEN}")
    req.add_header("Content-Type", "application/json; charset=utf-8")

    try:
        with urllib.request.urlopen(req, timeout=_SEND_TIMEOUT) as resp:
            resp_body = resp.read().decode("utf-8", errors="replace")
            resp_data = json.loads(resp_body)
            if resp_data.get("ok"):
                logger.info(
                    "slack_plan_notifier: bot message sent to %s", _PLAN_CHANNEL
                )
                return True
            error_msg = resp_data.get("error") or "unknown"
            logger.warning("slack_plan_notifier: bot API error: %s", error_msg)
            return False
    except (urllib.error.HTTPError, urllib.error.URLError, OSError, ValueError) as exc:
        logger.warning("slack_plan_notifier: bot API error: %s", exc)
        return False


def notify_plan_generated(plan_data: Dict[str, Any]) -> None:
    """Send a Slack notification for a successfully generated media plan.

    This function is non-blocking: it fires the notification in a daemon
    thread so the caller is not delayed. If Slack credentials are missing,
    it logs a debug message and returns immediately.

    Args:
        plan_data: Dictionary containing plan generation details:
            - client_name: str
            - industry: str
            - budget: str or number
            - user_name: str (from Google auth or requester_name)
            - user_email: str (from Google auth or requester_email)
            - role_count: int
            - location_count: int
            - channel_count: int
            - channels_list: list[str] (channel names)
            - generation_time_seconds: float
            - job_id: str (for download link)
            - filename: str (result filename)
            - timestamp: str (ISO format)
    """
    if not _WEBHOOK_URL and not _BOT_TOKEN:
        logger.debug(
            "slack_plan_notifier: no SLACK_WEBHOOK_URL or SLACK_BOT_TOKEN set, "
            "skipping plan notification"
        )
        return

    def _send():
        try:
            blocks = _build_plan_notification_blocks(plan_data)
            client = plan_data.get("client_name") or "Unknown"
            user = plan_data.get("user_name") or "Unknown"
            fallback_text = f"New Media Plan Generated: {client} by {user}"

            # Try webhook first, then bot API
            sent = _send_via_webhook(blocks, fallback_text)
            if not sent:
                sent = _send_via_bot(blocks, fallback_text)
            if not sent:
                logger.warning(
                    "slack_plan_notifier: failed to send notification for job %s",
                    plan_data.get("job_id", "?"),
                )
        except Exception as exc:
            logger.error(
                "slack_plan_notifier: unexpected error: %s", exc, exc_info=True
            )

    t = threading.Thread(target=_send, daemon=True, name="slack-plan-notify")
    t.start()
