"""Repo-wide guard against the retired Indeed CPC band resurfacing.

The July-2026 CPC research (channel_benchmarks_seed.json refresh 336480d,
per-entry cited) retired the earlier-vintage Indeed general band
$0.25-$1.50. Between 2026-07-16 and 2026-07-21 SIX separate commits each
found and fixed another stale copy of it (ea06bb0, d88af8b, 3aefe6c,
4565acb, dd37a7d, plus the deep-data-file refresh that ships with this
test) -- the figure was duplicated across KBs, module fallbacks, chat
fallback strings, and RAG-served data files, and nothing failed when one
copy was refreshed without the others.

This module is the mechanism fix for that class:

  1. A tracked-file sweep asserts the retired band appears NOWHERE except
     an explicit allowlist (each entry carries its justification). A new
     copy -- pasted from an old doc, regenerated by an LLM, restored from
     a backup -- fails commit-time with instructions.
  2. Alignment pins tie every live surface that carries the CURRENT
     Indeed band to channel_benchmarks_seed.json (the cited source of
     truth). When the seed is next refreshed, every pinned copy fails
     loudly until updated from the same research -- one commit updates
     all surfaces, or the divergence is consciously re-baselined.

Sibling guards (different surfaces, same discipline):
  tests/test_cpc_monitor.py            seed <-> comprehensive KB
  tests/test_industry_kb_cpc_strings.py seed <-> industry KB strings
  tests/test_platform_benchmark_fallback.py registry <-> module fallbacks
  tests/test_nova_platform_comparison_honesty.py nova chat surface

Deliberately NOT swept: LinkedIn 5.26 and Indeed-median 0.92. Both
numerals are ambiguous across bases ($5.26 is ALSO WordStream's
legitimate Google all-industries CPC; 0.92 appears in unrelated metrics),
so a regex sweep would be a false-positive machine. Their structured
copies are pinned by the sibling guards above; divergent-basis carriers
(e.g. recruitment_benchmarks_2026_deep.json's Appcast-sourced median,
seed_vendor_profiles' dated sponsored-content figure) are labeled with
their own sources per the 42fe2d6 precedent.

Runs under pytest, or standalone:
``python3 tests/test_cpc_retired_figures.py``.
"""

from __future__ import annotations

import json
import re
import subprocess
import sys
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parent.parent
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

# The retired figure, in every form it has been found in so far:
#   "$0.25-$1.50"  (display strings)   [0.25, 1.50]  (numeric pairs)
#   "0.25-1.50"    (bare, changelog prose)
_RETIRED_INDEED_BAND = re.compile(
    r"\$0\.25\s*-\s*\$1\.50|\[\s*0\.25\s*,\s*1\.50\s*\]|0\.25-1\.50"
)

# Lines allowed to mention the retired band: {file: (allowed-line regex,
# justification)}. Scoped per-LINE, not per-file, so an unrelated stale copy
# creeping into the same file still fails. Anything else that matches must
# either be refreshed from the cited research or added here WITH a reason.
_ALLOWLIST: dict = {
    "research.py": (
        re.compile(r'"indeed_cpc_range":\s*\[0\.25,\s*1\.50\]'),
        "RECRUITMENT_AD_TREND_HISTORY: historical 2024/2025 rows in a dead "
        "table -- repo-wide grep (2026-07-16 review) found zero consumers "
        "beyond its own definition",
    ),
    "data/recruitment_industry_knowledge.json": (
        re.compile(r'"_refreshed_2026_07_16":'),
        "benchmarks.cost_per_click._refreshed_2026_07_16 changelog note "
        "describes the retirement itself (bare '0.25-1.50 -> 0.97-2.71')",
    ),
}

# Directories whose contents are not live surfaces. scripts/ is deliberately
# swept: refresh tooling writing a retired value back IS the failure class.
_SKIP_PREFIXES = ("tests/", "docs/", "rpi/", "data/backups/")


def _tracked_candidate_files() -> list:
    out = subprocess.run(
        ["git", "ls-files", "*.py", "*.json"],
        cwd=PROJECT_ROOT,
        capture_output=True,
        text=True,
        check=True,
    ).stdout.splitlines()
    return [f for f in out if not f.startswith(_SKIP_PREFIXES)]


def test_retired_indeed_band_appears_only_in_allowlisted_files():
    offenders = {}
    for rel in _tracked_candidate_files():
        allowed_line = _ALLOWLIST.get(rel, (None,))[0]
        try:
            text = (PROJECT_ROOT / rel).read_text(encoding="utf-8")
        except (OSError, UnicodeDecodeError):
            continue
        hits = [
            f"line {i}: {line.strip()[:120]}"
            for i, line in enumerate(text.splitlines(), 1)
            if _RETIRED_INDEED_BAND.search(line)
            and not (allowed_line and allowed_line.search(line))
        ]
        if hits:
            offenders[rel] = hits[:3]
    assert not offenders, (
        "Retired Indeed CPC band ($0.25-$1.50, retired by the cited "
        "July-2026 research in channel_benchmarks_seed.json) found in "
        "non-allowlisted files. Refresh each from the cited research "
        "(seed band + per-entry sources) or, if the mention is genuinely "
        "historical/dead, add it to _ALLOWLIST with a justification:\n"
        + json.dumps(offenders, indent=2)
    )


# ── Alignment pins: live copies of the CURRENT band <-> the cited seed ──


def _seed_band() -> tuple:
    with open(
        PROJECT_ROOT / "data" / "channel_benchmarks_seed.json", encoding="utf-8"
    ) as f:
        seed = json.load(f)
    for entry in seed["data"]:
        if entry.get("channel") == "indeed":
            rng = (entry.get("metadata") or {}).get("cpc_range") or {}
            return float(rng["min"]), float(rng["max"])
    raise AssertionError("indeed entry missing from channel_benchmarks_seed.json")


def _band_str() -> str:
    lo, hi = _seed_band()
    return f"${lo:.2f}-${hi:.2f}"


def _load(rel: str) -> dict:
    with open(PROJECT_ROOT / rel, encoding="utf-8") as f:
        return json.load(f)


def test_recruitment_benchmarks_deep_indeed_band_matches_seed():
    kb = _load("data/recruitment_benchmarks_deep.json")
    assert (
        kb["platform_cpc_benchmarks"]["indeed"]["average_cpc"] == _band_str()
    ), "refresh from the same cited research as the seed, or re-baseline consciously"


def test_platform_intelligence_deep_indeed_band_matches_seed():
    kb = _load("data/platform_intelligence_deep.json")
    assert (
        kb["platforms"]["indeed"]["avg_cpc"]["general"] == _band_str()
    ), "refresh from the same cited research as the seed, or re-baseline consciously"


def test_supply_ecosystem_indeed_bands_match_seed():
    kb = _load("data/supply_ecosystem_intelligence.json")
    band = _band_str()
    tier1 = kb["publisher_tiers"]["tier_1_premium"]["publishers"]["indeed"]
    assert tier1["avg_cpc_range"].startswith(
        band
    ), "publisher_tiers indeed avg_cpc_range no longer leads with the seed band"
    perf = kb["publisher_performance"]["indeed"]
    assert (
        perf["avg_cpc"] == band
    ), "publisher_performance indeed avg_cpc diverged from the seed band"
    faq = kb["frequently_asked_questions"]["what_is_the_typical_cpc_for_recruitment"]
    assert (
        f"{band} for Indeed" in faq
    ), "FAQ typical-CPC answer no longer quotes the seed band for Indeed"


if __name__ == "__main__":
    import pytest

    raise SystemExit(pytest.main([__file__, "-v"]))
