"""Repo-wide guard against the retired Indeed CPC band resurfacing.

The July-2026 CPC research (channel_benchmarks_seed.json refresh 336480d,
per-entry cited) retired the earlier-vintage Indeed general band
$0.25-$1.50. Between 2026-07-16 and 2026-07-21 SIX separate commits each
found and fixed another stale copy of it (ea06bb0, d88af8b, 3aefe6c,
4565acb, dd37a7d, plus the deep-data-file refresh that ships with this
test) -- the figure was duplicated across KBs, module fallbacks, chat
fallback strings, and RAG-served data files, and nothing failed when one
copy was refreshed without the others.

This module is the mechanism fix for that class:

  1. A tracked-file sweep asserts the retired band appears NOWHERE except
     an explicit allowlist (each entry carries its justification). A new
     copy -- pasted from an old doc, regenerated by an LLM, restored from
     a backup -- fails commit-time with instructions. The sweep matches
     every SHAPE the figure has been written in, not just its display
     string: 2026-07-25 the bare-JSON form {"min": 0.25, "max": 1.50}
     turned out to be a blind spot that had hidden two more live copies
     (ad_benchmarks_recruitment_2026.json, publisher_benchmarks_2026.json)
     through the entire cascade below AND past this guard's first version.
     A new carrier shape is a guard bug, not just a data bug -- widen the
     patterns, do not special-case the file.
  2. Alignment pins tie every live surface that carries the CURRENT
     Indeed band to channel_benchmarks_seed.json (the cited source of
     truth). When the seed is next refreshed, every pinned copy fails
     loudly until updated from the same research -- one commit updates
     all surfaces, or the divergence is consciously re-baselined.

Sibling guards (different surfaces, same discipline):
  tests/test_cpc_monitor.py            seed <-> comprehensive KB
  tests/test_industry_kb_cpc_strings.py seed <-> industry KB strings
  tests/test_platform_benchmark_fallback.py registry <-> module fallbacks
  tests/test_nova_platform_comparison_honesty.py nova chat surface

Deliberately NOT swept: LinkedIn 5.26 and Indeed-median 0.92. Both
numerals are ambiguous across bases ($5.26 is ALSO WordStream's
legitimate Google all-industries CPC; 0.92 appears in unrelated metrics),
so a regex sweep would be a false-positive machine. Their structured
copies are pinned by the sibling guards above; divergent-basis carriers
(e.g. recruitment_benchmarks_2026_deep.json's Appcast-sourced median,
seed_vendor_profiles' dated sponsored-content figure) are labeled with
their own sources per the 42fe2d6 precedent.

Runs under pytest, or standalone:
``python3 tests/test_cpc_retired_figures.py``.
"""

from __future__ import annotations

import json
import math
import re
import subprocess
import sys
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parent.parent
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

# The retired figure, in every form it has been found in so far:
#   "$0.25-$1.50"  (display strings)   [0.25, 1.50]  (numeric pairs)
#   "0.25-1.50"    (bare, changelog prose)
_RETIRED_INDEED_BAND = re.compile(
    r"\$0\.25\s*-\s*\$1\.50|\[\s*0\.25\s*,\s*1\.50\s*\]|0\.25-1\.50"
)

# The same figure as a bare JSON object -- {"min": 0.25, "max": 1.50} -- which
# none of the forms above match. That blind spot hid two more live copies
# (ad_benchmarks_recruitment_2026.json, publisher_benchmarks_2026.json) through
# the whole 2026-07-16 -> 07-21 cascade and past the first version of this
# guard; both were refreshed 2026-07-25 and are pinned below.
#
# BOTH keys are required, in either order and with any intervening keys in the
# same object: `"min": 0.25` alone is a false-positive machine (LinkedIn's
# message_ads_cost_per_send_usd is {"min": 0.25, "max": 0.80} in one of these
# very files). `[^{}]` keeps a match inside a single JSON object so a min from
# one object cannot pair with a max from its neighbour. Trailing-zero and
# following-digit guards keep 0.250/1.5/1.50 in and 0.251/1.55 out.
_MIN_0_25 = r'"min"\s*:\s*0\.250*(?!\d)'
_MAX_1_50 = r'"max"\s*:\s*1\.50*(?!\d)'
_RETIRED_INDEED_JSON_PAIR = re.compile(
    rf"{_MIN_0_25}[^{{}}]*?{_MAX_1_50}|{_MAX_1_50}[^{{}}]*?{_MIN_0_25}"
)

# Lines allowed to mention the retired band: {file: (allowed-line regex,
# justification)}. Scoped per-LINE, not per-file, so an unrelated stale copy
# creeping into the same file still fails. Anything else that matches must
# either be refreshed from the cited research or added here WITH a reason.
# For a JSON min/max pair the regex is tested against the match widened to
# its enclosing object (see _pair_context), not just the reported line -- so
# an allowlist entry can key on a sibling key such as "currency" that sits
# below the line the hit is reported on.
_ALLOWLIST: dict = {
    "research.py": (
        re.compile(r'"indeed_cpc_range":\s*\[0\.25,\s*1\.50\]'),
        "RECRUITMENT_AD_TREND_HISTORY: historical 2024/2025 rows in a dead "
        "table -- repo-wide grep (2026-07-16 review) found zero consumers "
        "beyond its own definition",
    ),
    "data/recruitment_industry_knowledge.json": (
        re.compile(r'"_refreshed_2026_07_16":'),
        "benchmarks.cost_per_click._refreshed_2026_07_16 changelog note "
        "describes the retirement itself (bare '0.25-1.50 -> 0.97-2.71')",
    ),
    "data/international_benchmarks_2026.json": (
        re.compile(r'"currency":\s*"(?:CAD|EUR)"'),
        "DIVERGENT BASIS, not drift: cpc_local bands denominated in a "
        "non-USD local currency. HelloWork (France) is 0.25-1.5 EUR -- a "
        "different publisher entirely -- and Indeed Canada is 0.25-1.5 CAD, "
        "the Canadian market, not the US typical-role band this guard "
        "tracks. Both sit in a per-country series where all 29 Indeed "
        "entries carry their own local band (Germany 0.2-1.5 EUR, "
        "Netherlands 0.2-1.5 EUR, UK 0.2-1.2 GBP, ...), so the shared "
        "numerals are a collision, not a copy. Refreshing either to the USD "
        "figure would corrupt the international data. The allowlist regex "
        "keys on the local-currency marker, so a USD-denominated copy of "
        "the retired band appearing in this file still fails.",
    ),
}

# Directories whose contents are not live surfaces. scripts/ is deliberately
# swept: refresh tooling writing a retired value back IS the failure class.
_SKIP_PREFIXES = ("tests/", "docs/", "rpi/", "data/backups/")


def _tracked_candidate_files() -> list:
    out = subprocess.run(
        ["git", "ls-files", "*.py", "*.json"],
        cwd=PROJECT_ROOT,
        capture_output=True,
        text=True,
        check=True,
    ).stdout.splitlines()
    return [f for f in out if not f.startswith(_SKIP_PREFIXES)]


def _pair_context(text: str, start: int, end: int) -> str:
    """A JSON min/max match widened to its enclosing object's remainder.

    The pair itself carries no discriminator -- real drift and a legitimate
    local-currency band look identical inside the match -- so allowlist
    entries need the sibling keys ("currency", the field name) that sit just
    outside it. Widen left to the start of the line and right through the
    object's closing brace.
    """
    left = text.rfind("\n", 0, start) + 1
    right = text.find("}", end)
    return text[left : len(text) if right == -1 else right + 1]


def _retired_band_hits(text: str) -> dict:
    """{line number: (line, allowlist-check context)} for every retired form.

    Single-line forms are matched per line, as before. The JSON min/max pair
    is matched against the whole file instead, because `\\s*` inside it spans
    newlines -- a pretty-printed object splits the pair across lines and no
    per-line scan can ever see it. Each pair hit is reported on the line it
    starts on.
    """
    lines = text.splitlines()
    hits: dict = {}
    for i, line in enumerate(lines, 1):
        if _RETIRED_INDEED_BAND.search(line):
            hits[i] = (line, line)
    for m in _RETIRED_INDEED_JSON_PAIR.finditer(text):
        lineno = text.count("\n", 0, m.start()) + 1
        line = lines[lineno - 1] if lineno <= len(lines) else ""
        hits.setdefault(lineno, (line, _pair_context(text, m.start(), m.end())))
    return dict(sorted(hits.items()))


def test_retired_indeed_band_appears_only_in_allowlisted_files():
    offenders = {}
    for rel in _tracked_candidate_files():
        allowed_line = _ALLOWLIST.get(rel, (None,))[0]
        try:
            text = (PROJECT_ROOT / rel).read_text(encoding="utf-8")
        except (OSError, UnicodeDecodeError):
            continue
        hits = [
            f"line {i}: {line.strip()[:120]}"
            for i, (line, context) in _retired_band_hits(text).items()
            if not (allowed_line and allowed_line.search(context))
        ]
        if hits:
            offenders[rel] = hits[:3]
    assert not offenders, (
        "Retired Indeed CPC band ($0.25-$1.50, retired by the cited "
        "July-2026 research in channel_benchmarks_seed.json) found in "
        "non-allowlisted files. Refresh each from the cited research "
        "(seed band + per-entry sources) or, if the mention is genuinely "
        "historical/dead, add it to _ALLOWLIST with a justification:\n"
        + json.dumps(offenders, indent=2)
    )


# ── Alignment pins: live copies of the CURRENT band <-> the cited seed ──


def _seed_band() -> tuple:
    with open(
        PROJECT_ROOT / "data" / "channel_benchmarks_seed.json", encoding="utf-8"
    ) as f:
        seed = json.load(f)
    for entry in seed["data"]:
        if entry.get("channel") == "indeed":
            rng = (entry.get("metadata") or {}).get("cpc_range") or {}
            return float(rng["min"]), float(rng["max"])
    raise AssertionError("indeed entry missing from channel_benchmarks_seed.json")


def _band_str() -> str:
    lo, hi = _seed_band()
    return f"${lo:.2f}-${hi:.2f}"


def _seed_point() -> float:
    """The band's single-point representative: geometric mean, 2dp.

    Surfaces that need ONE Indeed CPC rather than a range (cross-channel
    comparison tables, the live overlay's avg_cpc_typical) must not invent
    their own. The geometric mean is the convention already applied to
    LinkedIn in 2a2d983 -- sqrt(1.50 * 4.50) = 2.60 -- and it is what
    live_market_data.json already stores for Indeed.
    """
    lo, hi = _seed_band()
    return round(math.sqrt(lo * hi), 2)


def _load(rel: str) -> dict:
    with open(PROJECT_ROOT / rel, encoding="utf-8") as f:
        return json.load(f)


def test_recruitment_benchmarks_deep_indeed_band_matches_seed():
    kb = _load("data/recruitment_benchmarks_deep.json")
    assert (
        kb["platform_cpc_benchmarks"]["indeed"]["average_cpc"] == _band_str()
    ), "refresh from the same cited research as the seed, or re-baseline consciously"


def test_platform_intelligence_deep_indeed_band_matches_seed():
    kb = _load("data/platform_intelligence_deep.json")
    assert (
        kb["platforms"]["indeed"]["avg_cpc"]["general"] == _band_str()
    ), "refresh from the same cited research as the seed, or re-baseline consciously"


def test_supply_ecosystem_indeed_bands_match_seed():
    kb = _load("data/supply_ecosystem_intelligence.json")
    band = _band_str()
    tier1 = kb["publisher_tiers"]["tier_1_premium"]["publishers"]["indeed"]
    assert tier1["avg_cpc_range"].startswith(
        band
    ), "publisher_tiers indeed avg_cpc_range no longer leads with the seed band"
    perf = kb["publisher_performance"]["indeed"]
    assert (
        perf["avg_cpc"] == band
    ), "publisher_performance indeed avg_cpc diverged from the seed band"
    faq = kb["frequently_asked_questions"]["what_is_the_typical_cpc_for_recruitment"]
    assert (
        f"{band} for Indeed" in faq
    ), "FAQ typical-CPC answer no longer quotes the seed band for Indeed"


# The two KBs that stored the band as bare JSON numbers rather than a display
# string, and so slipped past both the sweep above and the six-commit cascade
# that preceded it. Pinned numerically, against the same seed.


def test_ad_benchmarks_indeed_band_matches_seed():
    rng = _load("data/ad_benchmarks_recruitment_2026.json")["indeed_sponsored"][
        "avg_cpc_range_usd"
    ]
    assert (float(rng["min"]), float(rng["max"])) == _seed_band(), (
        "ad_benchmarks_recruitment_2026.json indeed_sponsored.avg_cpc_range_usd "
        "diverged from the seed band -- refresh from the same cited research, "
        "or re-baseline consciously"
    )


def test_publisher_benchmarks_indeed_band_matches_seed():
    platforms = _load("data/publisher_benchmarks_2026.json")["platforms"]
    rng = next(p for p in platforms if p["name"] == "Indeed")["avg_cpc_range_usd"]
    assert (float(rng["min"]), float(rng["max"])) == _seed_band(), (
        "publisher_benchmarks_2026.json Indeed avg_cpc_range_usd diverged from "
        "the seed band -- refresh from the same cited research, or re-baseline "
        "consciously"
    )


def test_live_market_data_indeed_band_matches_seed():
    """The live overlay benchmark_registry reads -- also a bare-JSON carrier."""
    indeed = _load("data/live_market_data.json")["job_boards"]["indeed"]
    rng = indeed["cpc_range"]
    assert (float(rng["min"]), float(rng["max"])) == _seed_band(), (
        "live_market_data.json job_boards.indeed.cpc_range diverged from the "
        "seed band -- benchmark_registry serves this overlay on the primary "
        "path, so a stale copy here reaches live output"
    )
    assert float(indeed["avg_cpc_typical"]) == _seed_point(), (
        "live_market_data.json job_boards.indeed.avg_cpc_typical is no longer "
        f"the geometric mean of the seed band ({_seed_point()})"
    )


def test_single_point_indeed_cpcs_match_the_seed_band():
    """Surfaces quoting ONE Indeed CPC must not drift out of the band.

    Added 2026-07-25: refreshing the band alone left this table's Indeed row
    at a retired-vintage 0.75 -- BELOW the new floor -- so one KB file served
    two mutually exclusive typical Indeed CPCs, and nova's deep-search
    returned both in a single response. A range pin cannot catch that; a
    point pin can.
    """
    lo, hi = _seed_band()
    row = next(
        r
        for r in _load("data/ad_benchmarks_recruitment_2026.json")[
            "channel_comparison_recruitment"
        ]
        if r["channel"] == "Indeed Sponsored"
    )
    point = float(row["avg_cpc_usd"])
    assert point == _seed_point(), (
        f"ad_benchmarks_recruitment_2026.json channel_comparison Indeed "
        f"avg_cpc_usd {point} is not the seed band's geometric mean "
        f"({_seed_point()})"
    )
    assert lo <= point <= hi, (
        f"Indeed comparison-table CPC {point} sits outside the band "
        f"{lo}-{hi} asserted elsewhere in the same file"
    )


if __name__ == "__main__":
    import pytest

    raise SystemExit(pytest.main([__file__, "-v"]))
