"""Tests for end-to-end PROVENANCE on the Excel deliverable (S89 excel_provenance).

Verifies that the "Sources & Confidence" sheet surfaces data-source provenance
(source / vintage / confidence) and the "Joveo measured" warehouse signal
(cg_benchmarks real outcomes) when present, while staying fully additive and
gracefully no-op when provenance metadata is absent.

The Excel build runs offline (no network / LLM / Supabase) -- generate_excel_v2
accepts a plain data dict and we read the bytes back with openpyxl.

Runs under pytest, or standalone: ``python3 tests/test_excel_provenance.py``.
"""

import io
import sys
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(PROJECT_ROOT))

import openpyxl  # noqa: E402

import excel_v2  # noqa: E402


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------
def _minimal_data(**overrides) -> dict:
    """A minimal but realistic plan data dict for the v2 generator."""
    data = {
        "client_name": "Acme Health",
        "company_name": "Acme Health",
        "industry": "healthcare_medical",
        "budget": "$100,000",
        "locations": ["Dallas, TX"],
        "roles": ["Registered Nurse"],
        "target_roles": ["Registered Nurse"],
        "campaign_duration": "3 months",
        "hire_volume": "50",
        "work_environment": "onsite",
        "_enriched": {},
        "_synthesized": {},
        "_budget_allocation": {},
    }
    data.update(overrides)
    return data


def _build_and_load(data: dict):
    """Run the generator and return the openpyxl workbook + sources worksheet."""
    raw = excel_v2.generate_excel_v2(data)
    assert isinstance(raw, (bytes, bytearray)) and len(raw) > 0
    wb = openpyxl.load_workbook(io.BytesIO(raw))
    assert "Sources & Confidence" in wb.sheetnames
    return wb, wb["Sources & Confidence"]


def _sheet_text(ws) -> str:
    """Concatenate all non-empty string cell values on a worksheet."""
    parts = []
    for row in ws.iter_rows(values_only=True):
        for val in row:
            if val is not None:
                parts.append(str(val))
    return "\n".join(parts)


def _all_numeric(ws):
    """All numeric cell values on the sheet."""
    out = []
    for row in ws.iter_rows():
        for cell in row:
            if isinstance(cell.value, (int, float)) and not isinstance(
                cell.value, bool
            ):
                out.append((cell.value, cell.number_format))
    return out


# ---------------------------------------------------------------------------
# Tests
# ---------------------------------------------------------------------------
def test_provenance_header_always_present():
    """The provenance section header appears even with no provenance metadata."""
    _wb, ws = _build_and_load(_minimal_data())
    text = _sheet_text(ws)
    # The section header carries the word "VINTAGE"; it always renders, even when
    # no per-source provenance metadata is attached (the table is conditional).
    assert "DATA PROVENANCE & VINTAGE" in text.upper()


def test_workbook_loads_and_is_valid():
    """openpyxl loads the generated bytes and the expected sheets exist."""
    wb, _ws = _build_and_load(_minimal_data())
    assert "Sources & Confidence" in wb.sheetnames
    # Other core sheets still present -- provenance is additive, not disruptive.
    assert any("Executive" in s for s in wb.sheetnames)


def test_kb_provenance_rows_render_source_vintage_confidence():
    """An explicit _enriched.provenance list surfaces source/vintage/confidence."""
    data = _minimal_data(
        _enriched={
            "provenance": [
                {
                    "source": "BLS Occupational Employment Statistics",
                    "vintage": "2025",
                    "confidence": "high",
                },
                {
                    "source": "Joveo Industry Benchmarks",
                    "data_year": "2026",
                    "confidence": 0.92,
                },
            ]
        }
    )
    _wb, ws = _build_and_load(data)
    text = _sheet_text(ws)
    assert "BLS Occupational Employment Statistics" in text
    assert "Joveo Industry Benchmarks" in text
    assert "2025" in text
    assert "2026" in text
    # The provenance table header renders its column titles when rows exist.
    assert "Data Source" in text and "Vintage" in text and "Confidence" in text
    # Numeric confidence (0.92) is normalized to a label, not a raw float string.
    assert "0.92" not in text


def test_warehouse_real_outcomes_signal_surfaced():
    """The cg_benchmarks measured signal renders title, cost/apply, sample size."""
    data = _minimal_data(
        _budget_allocation={
            "metadata": {
                "real_outcomes": {
                    "matched": True,
                    "title": "Registered Nurse",
                    "cost_per_apply": 4.06,
                    "avg_cost": 4.06,
                    "avg_applies": 8.0,
                    "sample_size": 303,
                    "last_updated": "2026-05-12",
                    "source": "cg_benchmarks",
                    "confidence": "measured",
                }
            }
        }
    )
    _wb, ws = _build_and_load(data)
    text = _sheet_text(ws)
    assert "Joveo Campaign Warehouse" in text
    assert "Registered Nurse" in text
    # Sample size written as a live number (303), cost-per-apply as a number (4.06).
    numerics = [v for v, _fmt in _all_numeric(ws)]
    assert 303 in numerics
    assert any(abs(v - 4.06) < 1e-6 for v in numerics)


def test_warehouse_signal_absent_is_graceful():
    """No real_outcomes -> warehouse subsection simply does not appear."""
    _wb, ws = _build_and_load(_minimal_data())
    text = _sheet_text(ws)
    assert "Joveo Campaign Warehouse" not in text
    # But the overall provenance header still renders.
    assert "DATA PROVENANCE & VINTAGE" in text.upper()


def test_no_match_outcomes_not_shown():
    """An unmatched warehouse result is not surfaced as a measured outcome."""
    data = _minimal_data(
        _budget_allocation={"metadata": {"real_outcomes": {"matched": False}}}
    )
    _wb, ws = _build_and_load(data)
    text = _sheet_text(ws)
    assert "Joveo Campaign Warehouse" not in text


def test_warehouse_accepts_list_of_outcomes():
    """real_outcomes may be a list; matched, usable rows are all surfaced."""
    data = _minimal_data(
        _budget_allocation={
            "metadata": {
                "real_outcomes": [
                    {
                        "matched": True,
                        "title": "RN - ICU",
                        "cost_per_apply": 3.50,
                        "sample_size": 120,
                        "last_updated": "2026-04-01",
                        "confidence": "measured",
                    },
                    {"matched": False},
                    {
                        "matched": True,
                        "title": "RN - ER",
                        "cost_per_apply": None,  # zero-applies edge: no cost/apply
                        "sample_size": 40,
                        "last_updated": "2026-03-01",
                        "confidence": "measured",
                    },
                ]
            }
        }
    )
    _wb, ws = _build_and_load(data)
    text = _sheet_text(ws)
    assert "RN - ICU" in text
    assert "RN - ER" in text
    numerics = [v for v, _fmt in _all_numeric(ws)]
    assert 120 in numerics and 40 in numerics
    # The None cost_per_apply degrades to the em-dash placeholder, not 0/None.
    assert "—" in text


def test_existing_confidence_assessment_preserved():
    """Provenance is additive: the legacy confidence assessment still renders."""
    data = _minimal_data(
        _synthesized={
            "confidence_scores": {"overall": 0.82},
            "_kb_age_days": 30,
        }
    )
    _wb, ws = _build_and_load(data)
    text = _sheet_text(ws)
    assert "Data Confidence Assessment".upper() in text.upper()
    # KB freshness signal flows into the provenance table as a source line.
    assert "Knowledge Base" in text


def test_section_metadata_vintage_collected():
    """Per-section metadata carrying source/vintage is collected defensively."""
    data = _minimal_data(
        _synthesized={
            "salary_data": {
                "metadata": {
                    "source": "CareerOneStop API",
                    "vintage": "2026 Q1",
                    "confidence": "medium",
                }
            }
        }
    )
    _wb, ws = _build_and_load(data)
    text = _sheet_text(ws)
    assert "CareerOneStop API" in text
    assert "2026 Q1" in text


# ---------------------------------------------------------------------------
# Unit-level checks on the collector / label helpers (no Excel build)
# ---------------------------------------------------------------------------
def test_confidence_label_normalization():
    assert excel_v2._provenance_confidence_label("measured") == "Measured"
    assert excel_v2._provenance_confidence_label(0.95) == "Verified"
    assert excel_v2._provenance_confidence_label(82) == "High"  # 0-100 tolerated
    assert excel_v2._provenance_confidence_label(None) == "Estimated"
    assert excel_v2._provenance_confidence_label("") == "Estimated"


def test_collect_kb_provenance_dedupes_and_handles_bad_shapes():
    data = {
        "_enriched": {
            "provenance": [
                {"source": "BLS", "vintage": "2025", "confidence": "high"},
                {"source": "BLS", "vintage": "2025", "confidence": "high"},  # dup
                "Plain String Source",
                12345,  # garbage entry ignored
            ]
        },
        "_synthesized": None,  # bad top-level shape tolerated
    }
    rows = excel_v2._collect_kb_provenance(data)
    sources = [r["source"] for r in rows]
    assert sources.count("BLS") == 1
    assert "Plain String Source" in sources


if __name__ == "__main__":
    _failures = 0
    for _name, _fn in sorted(globals().items()):
        if _name.startswith("test_") and callable(_fn):
            try:
                _fn()
                print(f"PASS {_name}")
            except AssertionError as exc:
                _failures += 1
                print(f"FAIL {_name}: {exc}")
            except Exception as exc:  # noqa: BLE001
                _failures += 1
                print(f"ERROR {_name}: {exc}")
    sys.exit(1 if _failures else 0)
